// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "180723_milestone-39-g501e0cd-dirty"
#define MICROPY_GIT_HASH "501e0cd-dirty"
#define MICROPY_BUILD_DATE "2019-07-05"
#define MICROPY_VERSION_MAJOR (0)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (1)
#define MICROPY_VERSION_STRING "0.0.1"
