// args= ['./make-pins.py', '--board', './fire1020evk/pins.csv', '--af', './1020_af.csv', '--pinmap', './mimxrt102x_pinmap.csv', '--prefix', './mimxrt102x_prefix.c', '--hdr', '../build-fire1020evk/genhdr/pins.h', '--qstr', '../build-fire1020evk/pins_qstr.h', '--af-const', '../build-fire1020evk/genhdr/pins_af_const.h', '--af-py', '../build-fire1020evk/pins_af.py']
// This file was automatically generated by make-pins.py
//
// --af ./1020_af.csv
// --pinmap ./mimxrt102x_pinmap.csv
// --board ./fire1020evk/pins.csv
// --prefix ./mimxrt102x_prefix.c

// <MCU>_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>

#include "py/obj.h"
#include "py/mphal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr, af_inSelReg, af_inSelVal) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .af_pin_type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .reg = (af_ptr), \
    .inSelReg = (af_inSelReg), \
    .inSelVal = (af_inSelVal), \
}

#define PIN(p_name, p_board_name, p_port, p_pin, p_af, p_adc_num, p_adc_channel, p_afReg, p_cfgReg) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_name, \
    .board_name = MP_QSTR_ ## p_board_name, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (sizeof(p_af) / sizeof(pin_af_obj_t)), \
    .pin_mask = (1UL << ((p_pin) & 0x1f)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
    .afReg = p_afReg, \
    .cfgReg = p_cfgReg, \
}

const pin_af_obj_t pin_AD_B0_12_af[] = {
  //( 0, ENET    ,  0, RX_ER           , ENET       , 0x401F8318U, 0x1U), // ENET_RX_ER
  AF( 1, LPSPI   ,  1, SDO             , LPSPI1     , 0x401F83A8U, 0x1U), // LPSPI1_SDO
  AF( 2, LPUART  ,  3, CTS_B           , LPUART3    , 0          , 0   ), // LPUART3_CTS_B
  //( 3, KPP     ,  0, COL2            , KPP        , 0          , 0   ), // KPP_COL2
  AF( 4, PWM     ,  2, PWMA1           , PWM2       , 0x401F834CU, 0x0U), // FLEXPWM2_PWMA1
  AF( 5, GPIO    ,  1, PIN12           , GPIO1      , 0          , 0   ), // GPIO1_PIN12
  //( 6, CM      ,  7, RT256_TRACE0    , CM7        , 0          , 0   ), // CM7_RT256_TRACE0
  //( 7, SNVS    ,  0, HP_VIO_5_CTL    , SNVS       , 0          , 0   ), // SNVS_HP_VIO_5_CTL
};

const pin_obj_t pin_AD_B0_12 = PIN(AD_B0_12, CN3_29_FLEXPWM2_A1, 1, 12, pin_AD_B0_12_af, PIN_ADC1, 0, 0x401F80ECU, 0x401F8260U);

const pin_af_obj_t pin_AD_B0_02_af[] = {
  //( 0, JTAG    ,  0, MUX_MOD         , JTAG       , 0          , 0   ), // JTAG_MUX_MOD
  AF( 5, GPIO    ,  1, PIN2            , GPIO1      , 0          , 0   ), // GPIO1_PIN2
  //( 6, ANATOP  ,  0, USBPHY1_TSTI_TX_LS_MODE, ANATOP     ,            ,     ), // ANATOP_USBPHY1_TSTI_TX_LS_MODE
  AF( 7, GPT     ,  1, CAPTURE1        , GPT1       , 0          , 0   ), // GPT1_CAPTURE1
};

const pin_obj_t pin_AD_B0_02 = PIN(AD_B0_02, CN3_8, 1, 2, pin_AD_B0_02_af, 0, 0, 0x401F80C4U, 0x401F8238U);

const pin_af_obj_t pin_AD_B0_03_af[] = {
  //( 0, JTAG    ,  0, MUX_TDI         , JTAG       , 0          , 0   ), // JTAG_MUX_TDI
  //( 1, USDHC   ,  2, CD_B            , USDHC2     , 0x401F8498U, 0x1U), // USDHC2_CD_B
  //( 2, WDOG    ,  1, WDOG_B          , WDOG1      , 0          , 0   ), // WDOG1_WDOG_B
  AF( 3, SAI     ,  1, MCLK            , SAI1       , 0x401F8430U, 0x1U), // SAI1_MCLK
  //( 4, USDHC   ,  1, WP              , USDHC1     , 0x401F8494U, 0x0U), // USDHC1_WP
  AF( 5, GPIO    ,  1, PIN3            , GPIO1      , 0          , 0   ), // GPIO1_PIN3
  //( 6, USB     ,  0, OTG1_OC         , USB        , 0x401F848CU, 0x0U), // USB_OTG1_OC
  //( 7, CCM     ,  0, PMIC_RDY        , CCM        , 0x401F8300U, 0x2U), // CCM_PMIC_RDY
};

const pin_obj_t pin_AD_B0_03 = PIN(AD_B0_03, CN3_4, 1, 3, pin_AD_B0_03_af, 0, 0, 0x401F80C8U, 0x401F823CU);

const pin_af_obj_t pin_AD_B0_04_af[] = {
  //( 0, JTAG    ,  0, MUX_TDO         , JTAG       , 0          , 0   ), // JTAG_MUX_TDO
  //( 1, FLEXCAN ,  1, TX              , FLEXCAN1   , 0          , 0   ), // FLEXCAN1_TX
  //( 2, USDHC   ,  1, WP              , USDHC1     , 0x401F8494U, 0x1U), // USDHC1_WP
  //( 3, QTIMER  ,  2, TIMER0          , QTIMER2    , 0x401F8420U, 0x1U), // QTIMER2_TIMER0
  //( 4, ENET    ,  0, MDIO            , ENET       , 0x401F8308U, 0x1U), // ENET_MDIO
  AF( 5, GPIO    ,  1, PIN4            , GPIO1      , 0          , 0   ), // GPIO1_PIN4
  //( 6, USB     ,  0, OTG1_PWR        , USB        , 0          , 0   ), // USB_OTG1_PWR
  //( 7, EWM     ,  0, EWM_OUT_B       , EWM        , 0          , 0   ), // EWM_EWM_OUT_B
};

const pin_obj_t pin_AD_B0_04 = PIN(AD_B0_04, CN3_24_QTIMER2_0, 1, 4, pin_AD_B0_04_af, 0, 0, 0x401F80CCU, 0x401F8240U);

const pin_af_obj_t pin_AD_B0_05_af[] = {
  //( 0, JTAG    ,  0, MUX_TRSTB       , JTAG       , 0          , 0   ), // JTAG_MUX_TRSTB
  //( 1, FLEXCAN ,  1, RX              , FLEXCAN1   , 0x401F8320U, 0x2U), // FLEXCAN1_RX
  //( 2, USDHC   ,  1, CD_B            , USDHC1     , 0x401F8490U, 0x1U), // USDHC1_CD_B
  //( 3, QTIMER  ,  2, TIMER1          , QTIMER2    , 0x401F8424U, 0x1U), // QTIMER2_TIMER1
  //( 4, ENET    ,  0, MDC             , ENET       , 0          , 0   ), // ENET_MDC
  AF( 5, GPIO    ,  1, PIN5            , GPIO1      , 0          , 0   ), // GPIO1_PIN5
  //( 6, ANATOP  ,  0, OTG1_ID         , ANATOP     , 0x401F82FCU, 0x0U), // ANATOP_OTG1_ID
  //( 7, NMI     ,  0, GLUE_NMI        , NMI        , 0x401F840CU, 0x0U), // NMI_GLUE_NMI
};

const pin_obj_t pin_AD_B0_05 = PIN(AD_B0_05, CN3_25_QTIMER2_1, 1, 5, pin_AD_B0_05_af, 0, 0, 0x401F80D0U, 0x401F8244U);

const pin_af_obj_t pin_AD_B0_06_af[] = {
  //( 0, PIT     ,  0, TRIGGER0        , PIT        , 0          , 0   ), // PIT_TRIGGER0
  //( 1, MQS     ,  0, RIGHT           , MQS        , 0          , 0   ), // MQS_RIGHT
  AF( 2, LPUART  ,  1, TX              , LPUART1    , 0          , 0   ), // LPUART1_TX
  //( 3, QTIMER  ,  2, TIMER2          , QTIMER2    , 0x401F8428U, 0x1U), // QTIMER2_TIMER2
  AF( 4, PWM     ,  2, PWMA3           , PWM2       , 0x401F8354U, 0x0U), // FLEXPWM2_PWMA3
  AF( 5, GPIO    ,  1, PIN6            , GPIO1      , 0          , 0   ), // GPIO1_PIN6
  //( 6, ANATOP  ,  0, 32K_OUT         , ANATOP     , 0          , 0   ), // ANATOP_32K_OUT
  //( 7, TPSMP   ,  0, LOAD_EN         , TPSMP      ,            ,     ), // TPSMP_LOAD_EN
};

const pin_obj_t pin_AD_B0_06 = PIN(AD_B0_06, CN3_22_UART1_TXD, 1, 6, pin_AD_B0_06_af, 0, 0, 0x401F80D4U, 0x401F8248U);

const pin_af_obj_t pin_AD_B0_07_af[] = {
  //( 0, PIT     ,  0, TRIGGER1        , PIT        , 0          , 0   ), // PIT_TRIGGER1
  //( 1, MQS     ,  0, LEFT            , MQS        , 0          , 0   ), // MQS_LEFT
  AF( 2, LPUART  ,  1, RX              , LPUART1    , 0          , 0   ), // LPUART1_RX
  //( 3, QTIMER  ,  2, TIMER3          , QTIMER2    , 0x401F842CU, 0x1U), // QTIMER2_TIMER3
  AF( 4, PWM     ,  2, PWMB3           , PWM2       , 0x401F8364U, 0x0U), // FLEXPWM2_PWMB3
  AF( 5, GPIO    ,  1, PIN7            , GPIO1      , 0          , 0   ), // GPIO1_PIN7
  //( 6, ANATOP  ,  0, 24M_OUT         , ANATOP     , 0          , 0   ), // ANATOP_24M_OUT
  //( 7, OBSERVE ,  0, MUX_OUT0        , OBSERVE    ,            ,     ), // OBSERVE_MUX_OUT0
};

const pin_obj_t pin_AD_B0_07 = PIN(AD_B0_07, CN3_21_UART1_RXD, 1, 7, pin_AD_B0_07_af, 0, 0, 0x401F80D8U, 0x401F824CU);

const pin_af_obj_t pin_AD_B0_08_af[] = {
  //( 0, ENET    ,  0, TX_CLK          , ENET       , 0x401F831CU, 0x1U), // ENET_TX_CLK
  AF( 1, LPI2C   ,  3, SCL             , LPI2C3     , 0x401F838CU, 0x1U), // LPI2C3_SCL
  AF( 2, LPUART  ,  1, CTS_B           , LPUART1    , 0          , 0   ), // LPUART1_CTS_B
  //( 3, KPP     ,  0, COL0            , KPP        , 0          , 0   ), // KPP_COL0
  //( 4, ENET    ,  0, REF_CLK1        , ENET       , 0x401F8304U, 0x1U), // ENET_REF_CLK1
  AF( 5, GPIO    ,  1, PIN8            , GPIO1      , 0          , 0   ), // GPIO1_PIN8
  //( 6, CM      ,  7, RT256_TXEV      , CM7        , 0          , 0   ), // CM7_RT256_TXEV
  //( 7, OBSERVE ,  0, MUX_OUT1        , OBSERVE    ,            ,     ), // OBSERVE_MUX_OUT1
};

const pin_obj_t pin_AD_B0_08 = PIN(AD_B0_08, CN3_26, 1, 8, pin_AD_B0_08_af, 0, 0, 0x401F80DCU, 0x401F8250U);

const pin_af_obj_t pin_AD_B0_09_af[] = {
  //( 0, ENET    ,  0, RDATA1          , ENET       , 0x401F8310U, 0x1U), // ENET_RDATA1
  AF( 1, LPI2C   ,  3, SDA             , LPI2C3     , 0x401F8390U, 0x1U), // LPI2C3_SDA
  AF( 2, LPUART  ,  1, RTS_B           , LPUART1    , 0          , 0   ), // LPUART1_RTS_B
  //( 3, KPP     ,  0, ROW0            , KPP        , 0          , 0   ), // KPP_ROW0
  //( 4, CSU     ,  0, CSU_INT_DEB     , CSU        ,            ,     ), // CSU_CSU_INT_DEB
  AF( 5, GPIO    ,  1, PIN9            , GPIO1      , 0          , 0   ), // GPIO1_PIN9
  //( 6, CM      ,  7, RT256_RXEV      , CM7        , 0          , 0   ), // CM7_RT256_RXEV
  //( 7, OBSERVE ,  0, MUX_OUT2        , OBSERVE    ,            ,     ), // OBSERVE_MUX_OUT2
};

const pin_obj_t pin_AD_B0_09 = PIN(AD_B0_09, CN3_28, 1, 9, pin_AD_B0_09_af, 0, 0, 0x401F80E0U, 0x401F8254U);

const pin_af_obj_t pin_AD_B0_10_af[] = {
  //( 0, ENET    ,  0, RDATA0          , ENET       , 0x401F830CU, 0x1U), // ENET_RDATA0
  AF( 1, LPSPI   ,  1, SCK             , LPSPI1     , 0x401F83A0U, 0x1U), // LPSPI1_SCK
  AF( 2, LPUART  ,  5, TX              , LPUART5    , 0x401F83F0U, 0x0U), // LPUART5_TX
  //( 3, KPP     ,  0, COL1            , KPP        , 0          , 0   ), // KPP_COL1
  AF( 4, PWM     ,  2, PWMA2           , PWM2       , 0x401F8350U, 0x0U), // FLEXPWM2_PWMA2
  AF( 5, GPIO    ,  1, PIN10           , GPIO1      , 0          , 0   ), // GPIO1_PIN10
  //( 6, CM      ,  7, RT256_TRACE_CLK , CM7        , 0          , 0   ), // CM7_RT256_TRACE_CLK
  //( 7, OBSERVE ,  0, MUX_OUT3        , OBSERVE    ,            ,     ), // OBSERVE_MUX_OUT3
};

const pin_obj_t pin_AD_B0_10 = PIN(AD_B0_10, CN3_27_FLEXPWM2_A2, 1, 10, pin_AD_B0_10_af, 0, 0, 0x401F80E4U, 0x401F8258U);

const pin_af_obj_t pin_AD_B0_11_af[] = {
  //( 0, ENET    ,  0, RX_EN           , ENET       , 0x401F8314U, 0x1U), // ENET_RX_EN
  AF( 1, LPSPI   ,  1, PCS0            , LPSPI1     , 0x401F839CU, 0x1U), // LPSPI1_PCS0
  AF( 2, LPUART  ,  5, RX              , LPUART5    , 0x401F83ECU, 0x0U), // LPUART5_RX
  //( 3, KPP     ,  0, ROW1            , KPP        , 0          , 0   ), // KPP_ROW1
  AF( 4, PWM     ,  2, PWMB2           , PWM2       , 0x401F8360U, 0x0U), // FLEXPWM2_PWMB2
  AF( 5, GPIO    ,  1, PIN11           , GPIO1      , 0          , 0   ), // GPIO1_PIN11
  //( 6, CM      ,  7, RT256_TRACE_SWO , CM7        , 0          , 0   ), // CM7_RT256_TRACE_SWO
  //( 7, OBSERVE ,  0, MUX_OUT4        , OBSERVE    ,            ,     ), // OBSERVE_MUX_OUT4
};

const pin_obj_t pin_AD_B0_11 = PIN(AD_B0_11, CN3_30_FLEXPWM2_B2, 1, 11, pin_AD_B0_11_af, 0, 0, 0x401F80E8U, 0x401F825CU);

const pin_af_obj_t pin_AD_B0_13_af[] = {
  //( 0, ENET    ,  0, TX_EN           , ENET       , 0          , 0   ), // ENET_TX_EN
  AF( 1, LPSPI   ,  1, SDI             , LPSPI1     , 0x401F83A4U, 0x1U), // LPSPI1_SDI
  AF( 2, LPUART  ,  3, RTS_B           , LPUART3    , 0          , 0   ), // LPUART3_RTS_B
  //( 3, KPP     ,  0, ROW2            , KPP        , 0          , 0   ), // KPP_ROW2
  AF( 4, PWM     ,  2, PWMB1           , PWM2       , 0x401F835CU, 0x0U), // FLEXPWM2_PWMB1
  AF( 5, GPIO    ,  1, PIN13           , GPIO1      , 0          , 0   ), // GPIO1_PIN13
  //( 6, CM      ,  7, RT256_TRACE1    , CM7        , 0          , 0   ), // CM7_RT256_TRACE1
  //( 7, SNVS    ,  0, HP_VIO_5_B      , SNVS       , 0          , 0   ), // SNVS_HP_VIO_5_B
};

const pin_obj_t pin_AD_B0_13 = PIN(AD_B0_13, CN3_32_FLEXPWM2_B1, 1, 13, pin_AD_B0_13_af, PIN_ADC2, 0, 0x401F80F0U, 0x401F8264U);

const pin_af_obj_t pin_AD_B0_14_af[] = {
  //( 0, ENET    ,  0, TDATA0          , ENET       , 0          , 0   ), // ENET_TDATA0
  //( 1, FLEXCAN ,  2, TX              , FLEXCAN2   , 0          , 0   ), // FLEXCAN2_TX
  AF( 2, LPUART  ,  3, TX              , LPUART3    , 0x401F83DCU, 0x1U), // LPUART3_TX
  //( 3, KPP     ,  0, COL3            , KPP        , 0          , 0   ), // KPP_COL3
  AF( 4, PWM     ,  2, PWMA0           , PWM2       , 0x401F8348U, 0x0U), // FLEXPWM2_PWMA0
  AF( 5, GPIO    ,  1, PIN14           , GPIO1      , 0          , 0   ), // GPIO1_PIN14
  //( 6, CM      ,  7, RT256_TRACE2    , CM7        , 0          , 0   ), // CM7_RT256_TRACE2
  //( 7, WDOG    ,  1, WDOG_ANY        , WDOG1      , 0          , 0   ), // WDOG1_WDOG_ANY
};

const pin_obj_t pin_AD_B0_14 = PIN(AD_B0_14, CN3_31_ADC12_1, 1, 14, pin_AD_B0_14_af, PIN_ADC1 | PIN_ADC2, 1, 0x401F80F4U, 0x401F8268U);

const pin_af_obj_t pin_AD_B0_15_af[] = {
  //( 0, ENET    ,  0, TDATA1          , ENET       , 0          , 0   ), // ENET_TDATA1
  //( 1, FLEXCAN ,  2, RX              , FLEXCAN2   , 0x401F8324U, 0x2U), // FLEXCAN2_RX
  AF( 2, LPUART  ,  3, RX              , LPUART3    , 0x401F83D8U, 0x1U), // LPUART3_RX
  //( 3, KPP     ,  0, ROW3            , KPP        , 0          , 0   ), // KPP_ROW3
  AF( 4, PWM     ,  2, PWMB0           , PWM2       , 0x401F8358U, 0x0U), // FLEXPWM2_PWMB0
  AF( 5, GPIO    ,  1, PIN15           , GPIO1      , 0          , 0   ), // GPIO1_PIN15
  //( 6, CM      ,  7, RT256_TRACE3    , CM7        , 0          , 0   ), // CM7_RT256_TRACE3
  //( 7, OCOTP   ,  0, FUSE_LATCHED    , OCOTP      ,            ,     ), // OCOTP_FUSE_LATCHED
};

const pin_obj_t pin_AD_B0_15 = PIN(AD_B0_15, CN3_34_ADC12_2, 1, 15, pin_AD_B0_15_af, PIN_ADC1 | PIN_ADC2, 2, 0x401F80F8U, 0x401F826CU);

const pin_af_obj_t pin_AD_B1_00_af[] = {
  //( 0, SEMC    ,  0, RDY             , SEMC       , 0x401F8484U, 0x0U), // SEMC_RDY
  //( 1, FLEXSPI ,  0, BUS2BIT_A_DATA3 , FLEXSPI    , 0x401F8374U, 0x1U), // FLEXSPI_BUS2BIT_A_DATA3
  //( 2, FLEXCAN ,  2, TX              , FLEXCAN2   , 0          , 0   ), // FLEXCAN2_TX
  AF( 3, SAI     ,  1, MCLK            , SAI1       , 0x401F8430U, 0x2U), // SAI1_MCLK
  //( 4, FLEXIO  ,  1, FLEXIO15        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO15
  AF( 5, GPIO    ,  1, PIN16           , GPIO1      , 0          , 0   ), // GPIO1_PIN16
  //( 6, ENET    ,  0, 1588_EVENT2_OUT , ENET       , 0          , 0   ), // ENET_1588_EVENT2_OUT
  //( 7, KPP     ,  0, COL4            , KPP        , 0          , 0   ), // KPP_COL4
};

const pin_obj_t pin_AD_B1_00 = PIN(AD_B1_00, CN3_15, 1, 16, pin_AD_B1_00_af, 0, 0, 0x401F80FCU, 0x401F8270U);

const pin_af_obj_t pin_AD_B1_01_af[] = {
  //( 0, SEMC    ,  0, CSX0            , SEMC       , 0          , 0   ), // SEMC_CSX0
  //( 1, FLEXSPI ,  0, BUS2BIT_A_SCLK  , FLEXSPI    , 0x401F8378U, 0x1U), // FLEXSPI_BUS2BIT_A_SCLK
  //( 2, FLEXCAN ,  2, RX              , FLEXCAN2   , 0x401F8324U, 0x3U), // FLEXCAN2_RX
  AF( 3, SAI     ,  1, TX_BCLK         , SAI1       , 0x401F844CU, 0x1U), // SAI1_TX_BCLK
  //( 4, FLEXIO  ,  1, FLEXIO14        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO14
  AF( 5, GPIO    ,  1, PIN17           , GPIO1      , 0          , 0   ), // GPIO1_PIN17
  //( 6, ENET    ,  0, 1588_EVENT2_IN  , ENET       , 0          , 0   ), // ENET_1588_EVENT2_IN
  //( 7, KPP     ,  0, ROW4            , KPP        , 0          , 0   ), // KPP_ROW4
};

const pin_obj_t pin_AD_B1_01 = PIN(AD_B1_01, CN3_13, 1, 17, pin_AD_B1_01_af, PIN_ADC1, 3, 0x401F8100U, 0x401F8274U);

const pin_af_obj_t pin_AD_B1_02_af[] = {
  //( 0, SEMC    ,  0, CSX1            , SEMC       , 0          , 0   ), // SEMC_CSX1
  //( 1, FLEXSPI ,  0, BUS2BIT_A_DATA0 , FLEXSPI    , 0x401F8368U, 0x1U), // FLEXSPI_BUS2BIT_A_DATA0
  AF( 2, LPSPI   ,  4, SCK             , LPSPI4     , 0x401F83C0U, 0x0U), // LPSPI4_SCK
  AF( 3, SAI     ,  1, TX_SYNC         , SAI1       , 0x401F8450U, 0x1U), // SAI1_TX_SYNC
  //( 4, FLEXIO  ,  1, FLEXIO13        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO13
  AF( 5, GPIO    ,  1, PIN18           , GPIO1      , 0          , 0   ), // GPIO1_PIN18
  //( 6, ENET    ,  0, 1588_EVENT3_OUT , ENET       , 0          , 0   ), // ENET_1588_EVENT3_OUT
  //( 7, KPP     ,  0, COL5            , KPP        , 0          , 0   ), // KPP_COL5
};

const pin_obj_t pin_AD_B1_02 = PIN(AD_B1_02, CN3_11_SPI4_SCK, 1, 18, pin_AD_B1_02_af, PIN_ADC2, 3, 0x401F8104U, 0x401F8278U);

const pin_af_obj_t pin_AD_B1_03_af[] = {
  //( 0, SEMC    ,  0, CSX2            , SEMC       , 0          , 0   ), // SEMC_CSX2
  //( 1, FLEXSPI ,  0, BUS2BIT_A_DATA2 , FLEXSPI    , 0x401F8370U, 0x1U), // FLEXSPI_BUS2BIT_A_DATA2
  AF( 2, LPSPI   ,  4, PCS0            , LPSPI4     , 0x401F83BCU, 0x0U), // LPSPI4_PCS0
  AF( 3, SAI     ,  1, TX_DATA0        , SAI1       , 0          , 0   ), // SAI1_TX_DATA0
  //( 4, FLEXIO  ,  1, FLEXIO12        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO12
  AF( 5, GPIO    ,  1, PIN19           , GPIO1      , 0          , 0   ), // GPIO1_PIN19
  //( 6, ENET    ,  0, 1588_EVENT3_IN  , ENET       , 0          , 0   ), // ENET_1588_EVENT3_IN
  //( 7, KPP     ,  0, ROW5            , KPP        , 0          , 0   ), // KPP_ROW5
};

const pin_obj_t pin_AD_B1_03 = PIN(AD_B1_03, CN3_9_SPI4_CS0, 1, 19, pin_AD_B1_03_af, PIN_ADC1, 4, 0x401F8108U, 0x401F827CU);

const pin_af_obj_t pin_AD_B1_04_af[] = {
  //( 0, SEMC    ,  0, CSX3            , SEMC       , 0          , 0   ), // SEMC_CSX3
  //( 1, FLEXSPI ,  0, BUS2BIT_A_DATA1 , FLEXSPI    , 0x401F836CU, 0x1U), // FLEXSPI_BUS2BIT_A_DATA1
  AF( 2, LPSPI   ,  4, SDO             , LPSPI4     , 0x401F83C8U, 0x0U), // LPSPI4_SDO
  AF( 3, SAI     ,  1, RX_SYNC         , SAI1       , 0x401F8448U, 0x0U), // SAI1_RX_SYNC
  //( 4, FLEXIO  ,  1, FLEXIO11        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO11
  AF( 5, GPIO    ,  1, PIN20           , GPIO1      , 0          , 0   ), // GPIO1_PIN20
  //( 6, LPSPI   ,  1, PCS1            , LPSPI1     , 0          , 0   ), // LPSPI1_PCS1
  //( 7, KPP     ,  0, COL6            , KPP        , 0          , 0   ), // KPP_COL6
};

const pin_obj_t pin_AD_B1_04 = PIN(AD_B1_04, CN3_7_SPI4_SD0, 1, 20, pin_AD_B1_04_af, PIN_ADC2, 4, 0x401F810CU, 0x401F8280U);

const pin_af_obj_t pin_AD_B1_05_af[] = {
  //( 0, USDHC   ,  1, WP              , USDHC1     , 0x401F8494U, 0x2U), // USDHC1_WP
  //( 1, FLEXSPI ,  0, BUS2BIT_A_SS0_B , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_A_SS0_B
  AF( 2, LPSPI   ,  4, SDI             , LPSPI4     , 0x401F83C4U, 0x0U), // LPSPI4_SDI
  AF( 3, SAI     ,  1, RX_DATA0        , SAI1       , 0x401F8438U, 0x1U), // SAI1_RX_DATA0
  //( 4, FLEXIO  ,  1, FLEXIO10        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO10
  AF( 5, GPIO    ,  1, PIN21           , GPIO1      , 0          , 0   ), // GPIO1_PIN21
  //( 6, LPSPI   ,  1, PCS2            , LPSPI1     , 0          , 0   ), // LPSPI1_PCS2
  //( 7, KPP     ,  0, ROW6            , KPP        , 0          , 0   ), // KPP_ROW6
};

const pin_obj_t pin_AD_B1_05 = PIN(AD_B1_05, CN3_5_SPI4_SDI, 1, 21, pin_AD_B1_05_af, PIN_ADC1 | PIN_ADC2, 5, 0x401F8110U, 0x401F8284U);

const pin_af_obj_t pin_AD_B1_06_af[] = {
  //( 0, USDHC   ,  1, RESET_B         , USDHC1     , 0          , 0   ), // USDHC1_RESET_B
  AF( 1, PWM     ,  1, PWMA0           , PWM1       , 0x401F8328U, 0x0U), // FLEXPWM1_PWMA0
  AF( 2, LPUART  ,  2, CTS_B           , LPUART2    , 0x401F83CCU, 0x0U), // LPUART2_CTS_B
  AF( 3, SAI     ,  1, RX_BCLK         , SAI1       , 0x401F8434U, 0x0U), // SAI1_RX_BCLK
  //( 4, FLEXIO  ,  1, FLEXIO9         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO9
  AF( 5, GPIO    ,  1, PIN22           , GPIO1      , 0          , 0   ), // GPIO1_PIN22
  //( 6, LPSPI   ,  1, PCS3            , LPSPI1     , 0          , 0   ), // LPSPI1_PCS3
  //( 7, KPP     ,  0, COL7            , KPP        , 0          , 0   ), // KPP_COL7
};

const pin_obj_t pin_AD_B1_06 = PIN(AD_B1_06, CN3_3_ADC12_6, 1, 22, pin_AD_B1_06_af, PIN_ADC1 | PIN_ADC2, 6, 0x401F8114U, 0x401F8288U);

const pin_af_obj_t pin_AD_B1_07_af[] = {
  //( 0, USDHC   ,  1, VSELECT         , USDHC1     , 0          , 0   ), // USDHC1_VSELECT
  AF( 1, PWM     ,  1, PWMB0           , PWM1       , 0x401F8338U, 0x0U), // FLEXPWM1_PWMB0
  AF( 2, LPUART  ,  2, RTS_B           , LPUART2    , 0          , 0   ), // LPUART2_RTS_B
  AF( 3, SAI     ,  1, TX_DATA1        , SAI1       , 0x401F8444U, 0x0U), // SAI1_TX_DATA1
  //( 4, FLEXIO  ,  1, FLEXIO8         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO8
  AF( 5, GPIO    ,  1, PIN23           , GPIO1      , 0          , 0   ), // GPIO1_PIN23
  //( 6, LPSPI   ,  3, PCS3            , LPSPI3     , 0          , 0   ), // LPSPI3_PCS3
  //( 7, KPP     ,  0, ROW7            , KPP        , 0          , 0   ), // KPP_ROW7
};

const pin_obj_t pin_AD_B1_07 = PIN(AD_B1_07, CN3_1_ADC12_7, 1, 23, pin_AD_B1_07_af, PIN_ADC1 | PIN_ADC2, 7, 0x401F8118U, 0x401F828CU);

const pin_af_obj_t pin_AD_B1_08_af[] = {
  AF( 0, LPI2C   ,  2, SCL             , LPI2C2     , 0x401F8384U, 0x0U), // LPI2C2_SCL
  AF( 1, PWM     ,  1, PWMA1           , PWM1       , 0x401F832CU, 0x0U), // FLEXPWM1_PWMA1
  AF( 2, LPUART  ,  2, TX              , LPUART2    , 0x401F83D4U, 0x0U), // LPUART2_TX
  AF( 3, SAI     ,  1, TX_DATA2        , SAI1       , 0x401F8440U, 0x0U), // SAI1_TX_DATA2
  //( 4, FLEXIO  ,  1, FLEXIO7         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO7
  AF( 5, GPIO    ,  1, PIN24           , GPIO1      , 0          , 0   ), // GPIO1_PIN24
  //( 6, LPSPI   ,  3, PCS2            , LPSPI3     , 0          , 0   ), // LPSPI3_PCS2
  //( 7, XBAR    ,  1, XBAR_INOUT12    , XBAR1      , 0x401F84B4U, 0x1U), // XBAR1_XBAR_INOUT12
};

const pin_obj_t pin_AD_B1_08 = PIN(AD_B1_08, LED1, 1, 24, pin_AD_B1_08_af, PIN_ADC1 | PIN_ADC2, 8, 0x401F811CU, 0x401F8290U);

const pin_af_obj_t pin_AD_B1_09_af[] = {
  AF( 0, LPI2C   ,  2, SDA             , LPI2C2     , 0x401F8388U, 0x0U), // LPI2C2_SDA
  AF( 1, PWM     ,  1, PWMB1           , PWM1       , 0x401F833CU, 0x0U), // FLEXPWM1_PWMB1
  AF( 2, LPUART  ,  2, RX              , LPUART2    , 0x401F83D0U, 0x0U), // LPUART2_RX
  AF( 3, SAI     ,  1, TX_DATA3        , SAI1       , 0x401F843CU, 0x0U), // SAI1_TX_DATA3
  //( 4, FLEXIO  ,  1, FLEXIO6         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO6
  AF( 5, GPIO    ,  1, PIN25           , GPIO1      , 0          , 0   ), // GPIO1_PIN25
  //( 6, LPSPI   ,  3, PCS1            , LPSPI3     , 0          , 0   ), // LPSPI3_PCS1
  //( 7, XBAR    ,  1, XBAR_INOUT13    , XBAR1      , 0x401F84B8U, 0x1U), // XBAR1_XBAR_INOUT13
};

const pin_obj_t pin_AD_B1_09 = PIN(AD_B1_09, LED2, 1, 25, pin_AD_B1_09_af, PIN_ADC1 | PIN_ADC2, 9, 0x401F8120U, 0x401F8294U);

const pin_af_obj_t pin_AD_B1_10_af[] = {
  //( 0, USB     ,  0, OTG1_PWR        , USB        , 0          , 0   ), // USB_OTG1_PWR
  AF( 1, PWM     ,  1, PWMA2           , PWM1       , 0x401F8330U, 0x0U), // FLEXPWM1_PWMA2
  AF( 2, LPUART  ,  4, TX              , LPUART4    , 0x401F83E8U, 0x1U), // LPUART4_TX
  //( 3, USDHC   ,  1, CD_B            , USDHC1     , 0x401F8490U, 0x2U), // USDHC1_CD_B
  //( 4, FLEXIO  ,  1, FLEXIO5         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO5
  AF( 5, GPIO    ,  1, PIN26           , GPIO1      , 0          , 0   ), // GPIO1_PIN26
  AF( 6, GPT     ,  2, CAPTURE1        , GPT2       , 0          , 0   ), // GPT2_CAPTURE1
  //( 7, TPSMP   ,  0, HDATA5          , TPSMP      ,            ,     ), // TPSMP_HDATA5
};

const pin_obj_t pin_AD_B1_10 = PIN(AD_B1_10, LED3, 1, 26, pin_AD_B1_10_af, PIN_ADC1 | PIN_ADC2, 10, 0x401F8124U, 0x401F8298U);

const pin_af_obj_t pin_AD_B1_11_af[] = {
  //( 0, ANATOP  ,  0, OTG1_ID         , ANATOP     , 0x401F82FCU, 0x1U), // ANATOP_OTG1_ID
  AF( 1, PWM     ,  1, PWMB2           , PWM1       , 0x401F8340U, 0x0U), // FLEXPWM1_PWMB2
  AF( 2, LPUART  ,  4, RX              , LPUART4    , 0x401F83E4U, 0x1U), // LPUART4_RX
  //( 3, USDHC   ,  1, WP              , USDHC1     , 0x401F8494U, 0x3U), // USDHC1_WP
  //( 4, FLEXIO  ,  1, FLEXIO4         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO4
  AF( 5, GPIO    ,  1, PIN27           , GPIO1      , 0          , 0   ), // GPIO1_PIN27
  AF( 6, GPT     ,  2, COMPARE1        , GPT2       , 0          , 0   ), // GPT2_COMPARE1
  //( 7, TPSMP   ,  0, HDATA4          , TPSMP      ,            ,     ), // TPSMP_HDATA4
};

const pin_obj_t pin_AD_B1_11 = PIN(AD_B1_11, CN3_14_ADC12_11, 1, 27, pin_AD_B1_11_af, PIN_ADC1 | PIN_ADC2, 11, 0x401F8128U, 0x401F829CU);

const pin_af_obj_t pin_AD_B1_12_af[] = {
  //( 0, USB     ,  0, OTG1_OC         , USB        , 0x401F848CU, 0x1U), // USB_OTG1_OC
  //( 1, ACMP    ,  0, OUT0            , ACMP       , 0          , 0   ), // ACMP_OUT0
  AF( 2, LPSPI   ,  3, SCK             , LPSPI3     , 0          , 0   ), // LPSPI3_SCK
  //( 3, USDHC   ,  2, CD_B            , USDHC2     , 0x401F8498U, 0x2U), // USDHC2_CD_B
  //( 4, FLEXIO  ,  1, FLEXIO3         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO3
  AF( 5, GPIO    ,  1, PIN28           , GPIO1      , 0          , 0   ), // GPIO1_PIN28
  AF( 6, PWM     ,  1, PWMA3           , PWM1       , 0x401F8334U, 0x0U), // FLEXPWM1_PWMA3
  //( 7, TPSMP   ,  0, HDATA3          , TPSMP      ,            ,     ), // TPSMP_HDATA3
};

const pin_obj_t pin_AD_B1_12 = PIN(AD_B1_12, CN3_16_ADC12_12, 1, 28, pin_AD_B1_12_af, PIN_ADC1 | PIN_ADC2, 12, 0x401F812CU, 0x401F82A0U);

const pin_af_obj_t pin_AD_B1_13_af[] = {
  //( 0, LPI2C   ,  1, HREQ            , LPI2C1     , 0          , 0   ), // LPI2C1_HREQ
  //( 1, ACMP    ,  0, OUT1            , ACMP       , 0          , 0   ), // ACMP_OUT1
  AF( 2, LPSPI   ,  3, PCS0            , LPSPI3     , 0          , 0   ), // LPSPI3_PCS0
  //( 3, USDHC   ,  2, WP              , USDHC2     , 0x401F849CU, 0x0U), // USDHC2_WP
  //( 4, FLEXIO  ,  1, FLEXIO2         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO2
  AF( 5, GPIO    ,  1, PIN29           , GPIO1      , 0          , 0   ), // GPIO1_PIN29
  AF( 6, PWM     ,  1, PWMB3           , PWM1       , 0x401F8344U, 0x0U), // FLEXPWM1_PWMB3
  //( 7, TPSMP   ,  0, HDATA2          , TPSMP      ,            ,     ), // TPSMP_HDATA2
};

const pin_obj_t pin_AD_B1_13 = PIN(AD_B1_13, LED4, 1, 29, pin_AD_B1_13_af, PIN_ADC1 | PIN_ADC2, 13, 0x401F8130U, 0x401F82A4U);

const pin_af_obj_t pin_AD_B1_14_af[] = {
  AF( 0, LPI2C   ,  1, SCL             , LPI2C1     , 0x401F837CU, 0x1U), // LPI2C1_SCL
  //( 1, ACMP    ,  0, OUT2            , ACMP       , 0          , 0   ), // ACMP_OUT2
  AF( 2, LPSPI   ,  3, SDO             , LPSPI3     , 0          , 0   ), // LPSPI3_SDO
  //( 3, ENET    ,  0, 1588_EVENT0_OUT , ENET       , 0          , 0   ), // ENET_1588_EVENT0_OUT
  //( 4, FLEXIO  ,  1, FLEXIO1         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO1
  AF( 5, GPIO    ,  1, PIN30           , GPIO1      , 0          , 0   ), // GPIO1_PIN30
  //( 6, CCM     ,  0, OUT2            , CCM        ,            ,     ), // CCM_OUT2
  //( 7, TPSMP   ,  0, HDATA1          , TPSMP      ,            ,     ), // TPSMP_HDATA1
};

const pin_obj_t pin_AD_B1_14 = PIN(AD_B1_14, CN3_17_I2C1_SCL, 1, 30, pin_AD_B1_14_af, PIN_ADC1 | PIN_ADC2, 14, 0x401F8134U, 0x401F82A8U);

const pin_af_obj_t pin_AD_B1_15_af[] = {
  AF( 0, LPI2C   ,  1, SDA             , LPI2C1     , 0x401F8380U, 0x1U), // LPI2C1_SDA
  //( 1, ACMP    ,  0, OUT3            , ACMP       , 0          , 0   ), // ACMP_OUT3
  AF( 2, LPSPI   ,  3, SDI             , LPSPI3     , 0          , 0   ), // LPSPI3_SDI
  //( 3, ENET    ,  0, 1588_EVENT0_IN  , ENET       , 0          , 0   ), // ENET_1588_EVENT0_IN
  //( 4, FLEXIO  ,  1, FLEXIO0         , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO0
  AF( 5, GPIO    ,  1, PIN31           , GPIO1      , 0          , 0   ), // GPIO1_PIN31
  //( 6, CCM     ,  0, DI0_EXT_CLK     , CCM        ,            ,     ), // CCM_DI0_EXT_CLK
  //( 7, TPSMP   ,  0, HDATA0          , TPSMP      ,            ,     ), // TPSMP_HDATA0
};

const pin_obj_t pin_AD_B1_15 = PIN(AD_B1_15, CN3_19_I2C1_SDA, 1, 31, pin_AD_B1_15_af, PIN_ADC1 | PIN_ADC2, 15, 0x401F8138U, 0x401F82ACU);

const pin_af_obj_t pin_EMC_40_af[] = {
  //( 0, SEMC    ,  0, CSX0            , SEMC       , 0          , 0   ), // SEMC_CSX0
  //( 1, XBAR    ,  1, XBAR_INOUT18    , XBAR1      , 0x401F84BCU, 0x1U), // XBAR1_XBAR_INOUT18
  //( 2, SPDIF   ,  0, OUT             , SPDIF      , 0          , 0   ), // SPDIF_OUT
  //( 3, ANATOP  ,  0, OTG1_ID         , ANATOP     , 0x401F82FCU, 0x2U), // ANATOP_OTG1_ID
  //( 4, ENET    ,  0, MDIO            , ENET       , 0x401F8308U, 0x2U), // ENET_MDIO
  AF( 5, GPIO    ,  3, PIN8            , GPIO3      , 0          , 0   ), // GPIO3_PIN8
  //( 6, ENET    ,  0, TDATA3          , ENET       , 0          , 0   ), // ENET_TDATA3
  AF( 7, GPT     ,  1, COMPARE3        , GPT1       , 0          , 0   ), // GPT1_COMPARE3
};

const pin_obj_t pin_EMC_40 = PIN(EMC_40, CN2_47_XBAR_INOUT, 3, 8, pin_EMC_40_af, 0, 0, 0x401F80B4U, 0x401F8228U);

const pin_af_obj_t pin_EMC_41_af[] = {
  //( 0, SEMC    ,  0, RDY             , SEMC       , 0x401F8484U, 0x1U), // SEMC_RDY
  //( 1, XBAR    ,  1, XBAR_INOUT19    , XBAR1      , 0x401F84C0U, 0x1U), // XBAR1_XBAR_INOUT19
  //( 2, SPDIF   ,  0, IN              , SPDIF      , 0x401F8488U, 0x1U), // SPDIF_IN
  //( 3, USB     ,  0, OTG1_PWR        , USB        , 0          , 0   ), // USB_OTG1_PWR
  //( 4, ENET    ,  0, MDC             , ENET       , 0          , 0   ), // ENET_MDC
  AF( 5, GPIO    ,  3, PIN9            , GPIO3      , 0          , 0   ), // GPIO3_PIN9
  //( 6, ENET    ,  0, TDATA2          , ENET       , 0          , 0   ), // ENET_TDATA2
  AF( 7, GPT     ,  1, COMPARE2        , GPT1       , 0          , 0   ), // GPT1_COMPARE2
};

const pin_obj_t pin_EMC_41 = PIN(EMC_41, CN2_27_XBAR_INOUT, 3, 9, pin_EMC_41_af, 0, 0, 0x401F80B8U, 0x401F822CU);

const pin_af_obj_t pin_SD_B0_06_af[] = {
  //( 0, USDHC   ,  1, CD_B            , USDHC1     , 0x401F8490U, 0x0U), // USDHC1_CD_B
  //( 1, USDHC   ,  1, RESET_B         , USDHC1     , 0          , 0   ), // USDHC1_RESET_B
  //( 2, ANATOP  ,  0, 32K_OUT         , ANATOP     , 0          , 0   ), // ANATOP_32K_OUT
  AF( 3, SAI     ,  2, TX_SYNC         , SAI2       , 0x401F8468U, 0x0U), // SAI2_TX_SYNC
  //( 4, WDOG    ,  1, WDOG_B          , WDOG1      , 0          , 0   ), // WDOG1_WDOG_B
  AF( 5, GPIO    ,  3, PIN19           , GPIO3      , 0          , 0   ), // GPIO3_PIN19
  //( 6, XBAR    ,  1, XBAR_INOUT17    , XBAR1      , 0x401F84ACU, 0x0U), // XBAR1_XBAR_INOUT17
  //( 7, TPSMP   ,  0, HADDR12         , TPSMP      ,            ,     ), // TPSMP_HADDR12
};

const pin_obj_t pin_SD_B0_06 = PIN(SD_B0_06, CN3_47, 3, 19, pin_SD_B0_06_af, 0, 0, 0x401F8154U, 0x401F82C8U);

const pin_af_obj_t pin_SD_B1_00_af[] = {
  //( 0, USDHC   ,  2, DATA2           , USDHC2     , 0          , 0   ), // USDHC2_DATA2
  //( 1, FLEXSPI ,  0, BUS2BIT_B_DATA3 , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_B_DATA3
  AF( 2, LPUART  ,  6, TX              , LPUART6    , 0x401F83F8U, 0x1U), // LPUART6_TX
  //( 3, XBAR    ,  1, XBAR_INOUT10    , XBAR1      , 0x401F84B0U, 0x1U), // XBAR1_XBAR_INOUT10
  //( 4, FLEXCAN ,  1, TX              , FLEXCAN1   , 0          , 0   ), // FLEXCAN1_TX
  AF( 5, GPIO    ,  3, PIN20           , GPIO3      , 0          , 0   ), // GPIO3_PIN20
  //( 6, CCM     ,  0, OUT0            , CCM        ,            ,     ), // CCM_OUT0
  //( 7, TPSMP   ,  0, HADDR11         , TPSMP      ,            ,     ), // TPSMP_HADDR11
};

const pin_obj_t pin_SD_B1_00 = PIN(SD_B1_00, CN2_50_UART6_TXD, 3, 20, pin_SD_B1_00_af, 0, 0, 0x401F8158U, 0x401F82CCU);

const pin_af_obj_t pin_SD_B1_01_af[] = {
  //( 0, USDHC   ,  2, DATA3           , USDHC2     , 0          , 0   ), // USDHC2_DATA3
  //( 1, FLEXSPI ,  0, BUS2BIT_B_SCLK  , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_B_SCLK
  AF( 2, LPUART  ,  6, RX              , LPUART6    , 0x401F83F4U, 0x1U), // LPUART6_RX
  //( 3, FLEXSPI ,  0, BUS2BIT_A_SS1_B , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_A_SS1_B
  //( 4, FLEXCAN ,  1, RX              , FLEXCAN1   , 0x401F8320U, 0x1U), // FLEXCAN1_RX
  AF( 5, GPIO    ,  3, PIN21           , GPIO3      , 0          , 0   ), // GPIO3_PIN21
  //( 6, CCM     ,  0, OUT1            , CCM        ,            ,     ), // CCM_OUT1
  //( 7, TPSMP   ,  0, HADDR10         , TPSMP      ,            ,     ), // TPSMP_HADDR10
};

const pin_obj_t pin_SD_B1_01 = PIN(SD_B1_01, CN2_54_UART6_RXD, 3, 21, pin_SD_B1_01_af, 0, 0, 0x401F815CU, 0x401F82D0U);

const pin_af_obj_t pin_SD_B1_02_af[] = {
  //( 0, USDHC   ,  2, CMD             , USDHC2     , 0          , 0   ), // USDHC2_CMD
  //( 1, FLEXSPI ,  0, BUS2BIT_B_DATA0 , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_B_DATA0
  AF( 2, LPUART  ,  8, TX              , LPUART8    , 0x401F8408U, 0x0U), // LPUART8_TX
  AF( 3, LPI2C   ,  4, SCL             , LPI2C4     , 0x401F8394U, 0x1U), // LPI2C4_SCL
  //( 4, ENET    ,  0, 1588_EVENT1_OUT , ENET       , 0          , 0   ), // ENET_1588_EVENT1_OUT
  AF( 5, GPIO    ,  3, PIN22           , GPIO3      , 0          , 0   ), // GPIO3_PIN22
  //( 6, CCM     ,  0, CLKO1           , CCM        , 0          , 0   ), // CCM_CLKO1
  //( 7, TPSMP   ,  0, HADDR9          , TPSMP      ,            ,     ), // TPSMP_HADDR9
};

const pin_obj_t pin_SD_B1_02 = PIN(SD_B1_02, CN2_51, 3, 22, pin_SD_B1_02_af, 0, 0, 0x401F8160U, 0x401F82D4U);

const pin_af_obj_t pin_SD_B1_03_af[] = {
  //( 0, USDHC   ,  2, CLK             , USDHC2     , 0          , 0   ), // USDHC2_CLK
  //( 1, FLEXSPI ,  0, BUS2BIT_B_DATA2 , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_B_DATA2
  AF( 2, LPUART  ,  8, RX              , LPUART8    , 0x401F8404U, 0x0U), // LPUART8_RX
  AF( 3, LPI2C   ,  4, SDA             , LPI2C4     , 0x401F8398U, 0x1U), // LPI2C4_SDA
  //( 4, ENET    ,  0, 1588_EVENT1_IN  , ENET       , 0          , 0   ), // ENET_1588_EVENT1_IN
  AF( 5, GPIO    ,  3, PIN23           , GPIO3      , 0          , 0   ), // GPIO3_PIN23
  //( 6, CCM     ,  0, CLKO2           , CCM        , 0          , 0   ), // CCM_CLKO2
  //( 7, TPSMP   ,  0, HADDR8          , TPSMP      ,            ,     ), // TPSMP_HADDR8
};

const pin_obj_t pin_SD_B1_03 = PIN(SD_B1_03, CN2_49, 3, 23, pin_SD_B1_03_af, 0, 0, 0x401F8164U, 0x401F82D8U);

const pin_af_obj_t pin_SD_B1_04_af[] = {
  //( 0, USDHC   ,  2, DATA0           , USDHC2     , 0          , 0   ), // USDHC2_DATA0
  //( 1, FLEXSPI ,  0, BUS2BIT_B_DATA1 , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_B_DATA1
  //( 2, ENET    ,  0, TX_CLK          , ENET       , 0x401F831CU, 0x0U), // ENET_TX_CLK
  //( 3, ENET    ,  0, REF_CLK1        , ENET       , 0x401F8304U, 0x0U), // ENET_REF_CLK1
  //( 4, EWM     ,  0, EWM_OUT_B       , EWM        , 0          , 0   ), // EWM_EWM_OUT_B
  AF( 5, GPIO    ,  3, PIN24           , GPIO3      , 0          , 0   ), // GPIO3_PIN24
  //( 6, CCM     ,  0, WAIT            , CCM        , 0          , 0   ), // CCM_WAIT
  //( 7, TPSMP   ,  0, HDATA15         , TPSMP      ,            ,     ), // TPSMP_HDATA15
};

const pin_obj_t pin_SD_B1_04 = PIN(SD_B1_04, CN2_52, 3, 24, pin_SD_B1_04_af, 0, 0, 0x401F8168U, 0x401F82DCU);

const pin_af_obj_t pin_SD_B1_05_af[] = {
  //( 0, USDHC   ,  2, DATA1           , USDHC2     , 0          , 0   ), // USDHC2_DATA1
  //( 1, FLEXSPI ,  0, BUS2BIT_A_DQS   , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_A_DQS
  //( 2, ENET    ,  0, RDATA1          , ENET       , 0x401F8310U, 0x0U), // ENET_RDATA1
  AF( 3, SAI     ,  3, MCLK            , SAI3       , 0x401F846CU, 0x0U), // SAI3_MCLK
  //( 4, FLEXSPI ,  0, BUS2BIT_B_SS0_B , FLEXSPI    , 0          , 0   ), // FLEXSPI_BUS2BIT_B_SS0_B
  AF( 5, GPIO    ,  3, PIN25           , GPIO3      , 0          , 0   ), // GPIO3_PIN25
  //( 6, CCM     ,  0, PMIC_RDY        , CCM        , 0x401F8300U, 0x1U), // CCM_PMIC_RDY
  //( 7, TPSMP   ,  0, HDATA14         , TPSMP      ,            ,     ), // TPSMP_HDATA14
};

const pin_obj_t pin_SD_B1_05 = PIN(SD_B1_05, CN2_53, 3, 25, pin_SD_B1_05_af, 0, 0, 0x401F816CU, 0x401F82E0U);

const pin_af_obj_t pin_WAKEUP_af[] = {
  AF( 5, GPIO    ,  5, PIN0            , GPIO5      , 0          , 0   ), // GPIO5_PIN0
  //( 7, NMI     ,  0, GLUE_NMI        , NMI        ,            ,     ), // NMI_GLUE_NMI
};

const pin_obj_t pin_WAKEUP = PIN(WAKEUP, KEY, 5, 0, pin_WAKEUP_af, 0, 0, 0x400A8000U, 0x400A8018U);

STATIC const mp_rom_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_AD_B0_12), MP_ROM_PTR(&pin_AD_B0_12) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_02), MP_ROM_PTR(&pin_AD_B0_02) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_03), MP_ROM_PTR(&pin_AD_B0_03) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_04), MP_ROM_PTR(&pin_AD_B0_04) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_05), MP_ROM_PTR(&pin_AD_B0_05) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_06), MP_ROM_PTR(&pin_AD_B0_06) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_07), MP_ROM_PTR(&pin_AD_B0_07) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_08), MP_ROM_PTR(&pin_AD_B0_08) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_09), MP_ROM_PTR(&pin_AD_B0_09) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_10), MP_ROM_PTR(&pin_AD_B0_10) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_11), MP_ROM_PTR(&pin_AD_B0_11) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_13), MP_ROM_PTR(&pin_AD_B0_13) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_14), MP_ROM_PTR(&pin_AD_B0_14) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_15), MP_ROM_PTR(&pin_AD_B0_15) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_00), MP_ROM_PTR(&pin_AD_B1_00) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_01), MP_ROM_PTR(&pin_AD_B1_01) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_02), MP_ROM_PTR(&pin_AD_B1_02) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_03), MP_ROM_PTR(&pin_AD_B1_03) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_04), MP_ROM_PTR(&pin_AD_B1_04) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_05), MP_ROM_PTR(&pin_AD_B1_05) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_06), MP_ROM_PTR(&pin_AD_B1_06) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_07), MP_ROM_PTR(&pin_AD_B1_07) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_08), MP_ROM_PTR(&pin_AD_B1_08) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_09), MP_ROM_PTR(&pin_AD_B1_09) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_10), MP_ROM_PTR(&pin_AD_B1_10) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_11), MP_ROM_PTR(&pin_AD_B1_11) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_12), MP_ROM_PTR(&pin_AD_B1_12) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_13), MP_ROM_PTR(&pin_AD_B1_13) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_14), MP_ROM_PTR(&pin_AD_B1_14) },
  { MP_ROM_QSTR(MP_QSTR_AD_B1_15), MP_ROM_PTR(&pin_AD_B1_15) },
  { MP_ROM_QSTR(MP_QSTR_EMC_40), MP_ROM_PTR(&pin_EMC_40) },
  { MP_ROM_QSTR(MP_QSTR_EMC_41), MP_ROM_PTR(&pin_EMC_41) },
  { MP_ROM_QSTR(MP_QSTR_SD_B0_06), MP_ROM_PTR(&pin_SD_B0_06) },
  { MP_ROM_QSTR(MP_QSTR_SD_B1_00), MP_ROM_PTR(&pin_SD_B1_00) },
  { MP_ROM_QSTR(MP_QSTR_SD_B1_01), MP_ROM_PTR(&pin_SD_B1_01) },
  { MP_ROM_QSTR(MP_QSTR_SD_B1_02), MP_ROM_PTR(&pin_SD_B1_02) },
  { MP_ROM_QSTR(MP_QSTR_SD_B1_03), MP_ROM_PTR(&pin_SD_B1_03) },
  { MP_ROM_QSTR(MP_QSTR_SD_B1_04), MP_ROM_PTR(&pin_SD_B1_04) },
  { MP_ROM_QSTR(MP_QSTR_SD_B1_05), MP_ROM_PTR(&pin_SD_B1_05) },
  { MP_ROM_QSTR(MP_QSTR_WAKEUP), MP_ROM_PTR(&pin_WAKEUP) },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_rom_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_LED1), MP_ROM_PTR(&pin_AD_B1_08) },
  { MP_ROM_QSTR(MP_QSTR_LED2), MP_ROM_PTR(&pin_AD_B1_09) },
  { MP_ROM_QSTR(MP_QSTR_LED3), MP_ROM_PTR(&pin_AD_B1_10) },
  { MP_ROM_QSTR(MP_QSTR_LED4), MP_ROM_PTR(&pin_AD_B1_13) },
  { MP_ROM_QSTR(MP_QSTR_KEY), MP_ROM_PTR(&pin_WAKEUP) },
  { MP_ROM_QSTR(MP_QSTR_CN2_49), MP_ROM_PTR(&pin_SD_B1_03) },
  { MP_ROM_QSTR(MP_QSTR_CN2_51), MP_ROM_PTR(&pin_SD_B1_02) },
  { MP_ROM_QSTR(MP_QSTR_CN2_52), MP_ROM_PTR(&pin_SD_B1_04) },
  { MP_ROM_QSTR(MP_QSTR_CN2_53), MP_ROM_PTR(&pin_SD_B1_05) },
  { MP_ROM_QSTR(MP_QSTR_CN3_4), MP_ROM_PTR(&pin_AD_B0_03) },
  { MP_ROM_QSTR(MP_QSTR_CN3_8), MP_ROM_PTR(&pin_AD_B0_02) },
  { MP_ROM_QSTR(MP_QSTR_CN3_13), MP_ROM_PTR(&pin_AD_B1_01) },
  { MP_ROM_QSTR(MP_QSTR_CN3_15), MP_ROM_PTR(&pin_AD_B1_00) },
  { MP_ROM_QSTR(MP_QSTR_CN3_26), MP_ROM_PTR(&pin_AD_B0_08) },
  { MP_ROM_QSTR(MP_QSTR_CN3_28), MP_ROM_PTR(&pin_AD_B0_09) },
  { MP_ROM_QSTR(MP_QSTR_CN3_47), MP_ROM_PTR(&pin_SD_B0_06) },
  { MP_ROM_QSTR(MP_QSTR_CN3_31_ADC12_1), MP_ROM_PTR(&pin_AD_B0_14) },
  { MP_ROM_QSTR(MP_QSTR_CN3_34_ADC12_2), MP_ROM_PTR(&pin_AD_B0_15) },
  { MP_ROM_QSTR(MP_QSTR_CN3_3_ADC12_6), MP_ROM_PTR(&pin_AD_B1_06) },
  { MP_ROM_QSTR(MP_QSTR_CN3_1_ADC12_7), MP_ROM_PTR(&pin_AD_B1_07) },
  { MP_ROM_QSTR(MP_QSTR_CN3_14_ADC12_11), MP_ROM_PTR(&pin_AD_B1_11) },
  { MP_ROM_QSTR(MP_QSTR_CN3_16_ADC12_12), MP_ROM_PTR(&pin_AD_B1_12) },
  { MP_ROM_QSTR(MP_QSTR_CN3_24_QTIMER2_0), MP_ROM_PTR(&pin_AD_B0_04) },
  { MP_ROM_QSTR(MP_QSTR_CN3_25_QTIMER2_1), MP_ROM_PTR(&pin_AD_B0_05) },
  { MP_ROM_QSTR(MP_QSTR_CN3_27_FLEXPWM2_A2), MP_ROM_PTR(&pin_AD_B0_10) },
  { MP_ROM_QSTR(MP_QSTR_CN3_30_FLEXPWM2_B2), MP_ROM_PTR(&pin_AD_B0_11) },
  { MP_ROM_QSTR(MP_QSTR_CN3_29_FLEXPWM2_A1), MP_ROM_PTR(&pin_AD_B0_12) },
  { MP_ROM_QSTR(MP_QSTR_CN3_32_FLEXPWM2_B1), MP_ROM_PTR(&pin_AD_B0_13) },
  { MP_ROM_QSTR(MP_QSTR_CN3_22_UART1_TXD), MP_ROM_PTR(&pin_AD_B0_06) },
  { MP_ROM_QSTR(MP_QSTR_CN3_21_UART1_RXD), MP_ROM_PTR(&pin_AD_B0_07) },
  { MP_ROM_QSTR(MP_QSTR_CN2_50_UART6_TXD), MP_ROM_PTR(&pin_SD_B1_00) },
  { MP_ROM_QSTR(MP_QSTR_CN2_54_UART6_RXD), MP_ROM_PTR(&pin_SD_B1_01) },
  { MP_ROM_QSTR(MP_QSTR_CN3_19_I2C1_SDA), MP_ROM_PTR(&pin_AD_B1_15) },
  { MP_ROM_QSTR(MP_QSTR_CN3_17_I2C1_SCL), MP_ROM_PTR(&pin_AD_B1_14) },
  { MP_ROM_QSTR(MP_QSTR_CN3_11_SPI4_SCK), MP_ROM_PTR(&pin_AD_B1_02) },
  { MP_ROM_QSTR(MP_QSTR_CN3_9_SPI4_CS0), MP_ROM_PTR(&pin_AD_B1_03) },
  { MP_ROM_QSTR(MP_QSTR_CN3_7_SPI4_SD0), MP_ROM_PTR(&pin_AD_B1_04) },
  { MP_ROM_QSTR(MP_QSTR_CN3_5_SPI4_SDI), MP_ROM_PTR(&pin_AD_B1_05) },
  { MP_ROM_QSTR(MP_QSTR_CN2_47_XBAR_INOUT), MP_ROM_PTR(&pin_EMC_40) },
  { MP_ROM_QSTR(MP_QSTR_CN2_27_XBAR_INOUT), MP_ROM_PTR(&pin_EMC_41) },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[] = {
  &pin_AD_B0_12, // 0
  &pin_AD_B0_14, // 1
  &pin_AD_B0_15, // 2
  &pin_AD_B1_01, // 3
  &pin_AD_B1_03, // 4
  &pin_AD_B1_05, // 5
  &pin_AD_B1_06, // 6
  &pin_AD_B1_07, // 7
  &pin_AD_B1_08, // 8
  &pin_AD_B1_09, // 9
  &pin_AD_B1_10, // 10
  &pin_AD_B1_11, // 11
  &pin_AD_B1_12, // 12
  &pin_AD_B1_13, // 13
  &pin_AD_B1_14, // 14
  &pin_AD_B1_15, // 15
  NULL,    // 16
};

const pin_obj_t * const pin_adc2[] = {
  &pin_AD_B0_13, // 0
  &pin_AD_B0_14, // 1
  &pin_AD_B0_15, // 2
  &pin_AD_B1_02, // 3
  &pin_AD_B1_04, // 4
  &pin_AD_B1_05, // 5
  &pin_AD_B1_06, // 6
  &pin_AD_B1_07, // 7
  &pin_AD_B1_08, // 8
  &pin_AD_B1_09, // 9
  &pin_AD_B1_10, // 10
  &pin_AD_B1_11, // 11
  &pin_AD_B1_12, // 12
  &pin_AD_B1_13, // 13
  &pin_AD_B1_14, // 14
  &pin_AD_B1_15, // 15
  NULL,    // 16
};

const pin_obj_t * const pin_acmp1[] = {
  &pin_AD_B0_14, // 0
  &pin_AD_B0_15, // 1
  &pin_AD_B1_00, // 2
  &pin_AD_B1_04, // 3
  &pin_AD_B0_08, // 4
  &pin_AD_B1_08, // 5
  &pin_AD_B1_12, // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
  NULL,    // 16
};

const pin_obj_t * const pin_acmp2[] = {
  &pin_AD_B0_14, // 0
  &pin_AD_B0_15, // 1
  &pin_AD_B1_01, // 2
  &pin_AD_B1_05, // 3
  &pin_AD_B0_09, // 4
  &pin_AD_B1_09, // 5
  &pin_AD_B1_13, // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
  NULL,    // 16
};

const pin_obj_t * const pin_acmp3[] = {
  &pin_AD_B0_14, // 0
  &pin_AD_B0_15, // 1
  &pin_AD_B1_02, // 2
  &pin_AD_B1_06, // 3
  &pin_AD_B0_10, // 4
  &pin_AD_B1_10, // 5
  &pin_AD_B1_14, // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
  NULL,    // 16
};

const pin_obj_t * const pin_acmp4[] = {
  &pin_AD_B0_14, // 0
  &pin_AD_B0_15, // 1
  &pin_AD_B1_03, // 2
  &pin_AD_B1_07, // 3
  &pin_AD_B0_11, // 4
  &pin_AD_B1_11, // 5
  &pin_AD_B1_15, // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
  NULL,    // 16
};
