// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "0.12-70-g53e08e6-dirty"
#define MICROPY_GIT_HASH "53e08e6-dirty"
#define OPENMV_GIT_TAG "0.12-70-g53e08e6-dirty"
#define OPENMV_GIT_HASH "53e08e6-dirty"
#define MICROPY_BUILD_DATE "2020-02-26"
