// Generated by make-pins.py, do NOT edit!
extern const pin_obj_t pin_AD_B0_13;
extern const pin_af_obj_t pin_AD_B0_13_af[];
extern const pin_obj_t pin_EMC_19;
extern const pin_af_obj_t pin_EMC_19_af[];
extern const pin_obj_t pin_EMC_20;
extern const pin_af_obj_t pin_EMC_20_af[];
extern const pin_obj_t pin_EMC_21;
extern const pin_af_obj_t pin_EMC_21_af[];
extern const pin_obj_t pin_EMC_22;
extern const pin_af_obj_t pin_EMC_22_af[];
extern const pin_obj_t pin_EMC_27;
extern const pin_af_obj_t pin_EMC_27_af[];
extern const pin_obj_t pin_EMC_28;
extern const pin_af_obj_t pin_EMC_28_af[];
extern const pin_obj_t pin_EMC_29;
extern const pin_af_obj_t pin_EMC_29_af[];
extern const pin_obj_t pin_EMC_30;
extern const pin_af_obj_t pin_EMC_30_af[];
extern const pin_obj_t pin_EMC_39;
extern const pin_af_obj_t pin_EMC_39_af[];
extern const pin_obj_t pin_EMC_40;
extern const pin_af_obj_t pin_EMC_40_af[];
extern const pin_obj_t pin_EMC_41;
extern const pin_af_obj_t pin_EMC_41_af[];
extern const pin_obj_t pin_WAKEUP;
extern const pin_af_obj_t pin_WAKEUP_af[];
extern const pin_obj_t * const pin_adc1[];
extern const pin_obj_t * const pin_adc2[];
extern const pin_obj_t * const pin_adc3[];
#define pyb_pin_LED_R pin_EMC_40
#define pyb_pin_LED_G pin_EMC_41
#define pyb_pin_LED_B pin_EMC_39
#define pyb_pin_KEY pin_WAKEUP
#define pyb_pin_P6 pin_AD_B0_13
#define pyb_pin_P7 pin_EMC_19
#define pyb_pin_P8 pin_EMC_20
#define pyb_pin_P0 pin_EMC_28
#define pyb_pin_P1 pin_EMC_29
#define pyb_pin_P2 pin_EMC_27
#define pyb_pin_P3 pin_EMC_30
#define pyb_pin_P4 pin_EMC_22
#define pyb_pin_P5 pin_EMC_21
