// Generated by make-pins.py, do NOT edit!
extern const pin_obj_t pin_AD_B0_12;
extern const pin_af_obj_t pin_AD_B0_12_af[];
extern const pin_obj_t pin_AD_B0_02;
extern const pin_af_obj_t pin_AD_B0_02_af[];
extern const pin_obj_t pin_AD_B0_03;
extern const pin_af_obj_t pin_AD_B0_03_af[];
extern const pin_obj_t pin_AD_B0_04;
extern const pin_af_obj_t pin_AD_B0_04_af[];
extern const pin_obj_t pin_AD_B0_05;
extern const pin_af_obj_t pin_AD_B0_05_af[];
extern const pin_obj_t pin_AD_B0_06;
extern const pin_af_obj_t pin_AD_B0_06_af[];
extern const pin_obj_t pin_AD_B0_07;
extern const pin_af_obj_t pin_AD_B0_07_af[];
extern const pin_obj_t pin_AD_B0_08;
extern const pin_af_obj_t pin_AD_B0_08_af[];
extern const pin_obj_t pin_AD_B0_09;
extern const pin_af_obj_t pin_AD_B0_09_af[];
extern const pin_obj_t pin_AD_B0_10;
extern const pin_af_obj_t pin_AD_B0_10_af[];
extern const pin_obj_t pin_AD_B0_11;
extern const pin_af_obj_t pin_AD_B0_11_af[];
extern const pin_obj_t pin_AD_B0_13;
extern const pin_af_obj_t pin_AD_B0_13_af[];
extern const pin_obj_t pin_AD_B0_14;
extern const pin_af_obj_t pin_AD_B0_14_af[];
extern const pin_obj_t pin_AD_B0_15;
extern const pin_af_obj_t pin_AD_B0_15_af[];
extern const pin_obj_t pin_AD_B1_00;
extern const pin_af_obj_t pin_AD_B1_00_af[];
extern const pin_obj_t pin_AD_B1_01;
extern const pin_af_obj_t pin_AD_B1_01_af[];
extern const pin_obj_t pin_AD_B1_02;
extern const pin_af_obj_t pin_AD_B1_02_af[];
extern const pin_obj_t pin_AD_B1_03;
extern const pin_af_obj_t pin_AD_B1_03_af[];
extern const pin_obj_t pin_AD_B1_04;
extern const pin_af_obj_t pin_AD_B1_04_af[];
extern const pin_obj_t pin_AD_B1_05;
extern const pin_af_obj_t pin_AD_B1_05_af[];
extern const pin_obj_t pin_AD_B1_06;
extern const pin_af_obj_t pin_AD_B1_06_af[];
extern const pin_obj_t pin_AD_B1_07;
extern const pin_af_obj_t pin_AD_B1_07_af[];
extern const pin_obj_t pin_AD_B1_08;
extern const pin_af_obj_t pin_AD_B1_08_af[];
extern const pin_obj_t pin_AD_B1_09;
extern const pin_af_obj_t pin_AD_B1_09_af[];
extern const pin_obj_t pin_AD_B1_10;
extern const pin_af_obj_t pin_AD_B1_10_af[];
extern const pin_obj_t pin_AD_B1_11;
extern const pin_af_obj_t pin_AD_B1_11_af[];
extern const pin_obj_t pin_AD_B1_12;
extern const pin_af_obj_t pin_AD_B1_12_af[];
extern const pin_obj_t pin_AD_B1_13;
extern const pin_af_obj_t pin_AD_B1_13_af[];
extern const pin_obj_t pin_AD_B1_14;
extern const pin_af_obj_t pin_AD_B1_14_af[];
extern const pin_obj_t pin_AD_B1_15;
extern const pin_af_obj_t pin_AD_B1_15_af[];
extern const pin_obj_t pin_EMC_40;
extern const pin_af_obj_t pin_EMC_40_af[];
extern const pin_obj_t pin_EMC_41;
extern const pin_af_obj_t pin_EMC_41_af[];
extern const pin_obj_t pin_SD_B0_06;
extern const pin_af_obj_t pin_SD_B0_06_af[];
extern const pin_obj_t pin_SD_B1_00;
extern const pin_af_obj_t pin_SD_B1_00_af[];
extern const pin_obj_t pin_SD_B1_01;
extern const pin_af_obj_t pin_SD_B1_01_af[];
extern const pin_obj_t pin_SD_B1_02;
extern const pin_af_obj_t pin_SD_B1_02_af[];
extern const pin_obj_t pin_SD_B1_03;
extern const pin_af_obj_t pin_SD_B1_03_af[];
extern const pin_obj_t pin_SD_B1_04;
extern const pin_af_obj_t pin_SD_B1_04_af[];
extern const pin_obj_t pin_SD_B1_05;
extern const pin_af_obj_t pin_SD_B1_05_af[];
extern const pin_obj_t pin_WAKEUP;
extern const pin_af_obj_t pin_WAKEUP_af[];
extern const pin_obj_t * const pin_adc1[];
extern const pin_obj_t * const pin_adc2[];
extern const pin_obj_t * const pin_adc3[];
#define pyb_pin_LED1 pin_AD_B1_08
#define pyb_pin_LED2 pin_AD_B1_09
#define pyb_pin_LED3 pin_AD_B1_10
#define pyb_pin_LED4 pin_AD_B1_13
#define pyb_pin_KEY pin_WAKEUP
#define pyb_pin_CN2_49 pin_SD_B1_03
#define pyb_pin_CN2_51 pin_SD_B1_02
#define pyb_pin_CN2_52 pin_SD_B1_04
#define pyb_pin_CN2_53 pin_SD_B1_05
#define pyb_pin_CN3_4 pin_AD_B0_03
#define pyb_pin_CN3_8 pin_AD_B0_02
#define pyb_pin_CN3_13 pin_AD_B1_01
#define pyb_pin_CN3_15 pin_AD_B1_00
#define pyb_pin_CN3_26 pin_AD_B0_08
#define pyb_pin_CN3_28 pin_AD_B0_09
#define pyb_pin_CN3_47 pin_SD_B0_06
#define pyb_pin_CN3_31_ADC12_1 pin_AD_B0_14
#define pyb_pin_CN3_34_ADC12_2 pin_AD_B0_15
#define pyb_pin_CN3_3_ADC12_6 pin_AD_B1_06
#define pyb_pin_CN3_1_ADC12_7 pin_AD_B1_07
#define pyb_pin_CN3_14_ADC12_11 pin_AD_B1_11
#define pyb_pin_CN3_16_ADC12_12 pin_AD_B1_12
#define pyb_pin_CN3_24_QTIMER2_0 pin_AD_B0_04
#define pyb_pin_CN3_25_QTIMER2_1 pin_AD_B0_05
#define pyb_pin_CN3_27_FLEXPWM2_A2 pin_AD_B0_10
#define pyb_pin_CN3_30_FLEXPWM2_B2 pin_AD_B0_11
#define pyb_pin_CN3_29_FLEXPWM2_A1 pin_AD_B0_12
#define pyb_pin_CN3_32_FLEXPWM2_B1 pin_AD_B0_13
#define pyb_pin_CN3_22_UART1_TXD pin_AD_B0_06
#define pyb_pin_CN3_21_UART1_RXD pin_AD_B0_07
#define pyb_pin_CN2_50_UART6_TXD pin_SD_B1_00
#define pyb_pin_CN2_54_UART6_RXD pin_SD_B1_01
#define pyb_pin_CN3_19_I2C1_SDA pin_AD_B1_15
#define pyb_pin_CN3_17_I2C1_SCL pin_AD_B1_14
#define pyb_pin_CN3_11_SPI4_SCK pin_AD_B1_02
#define pyb_pin_CN3_9_SPI4_CS0 pin_AD_B1_03
#define pyb_pin_CN3_7_SPI4_SD0 pin_AD_B1_04
#define pyb_pin_CN3_5_SPI4_SDI pin_AD_B1_05
#define pyb_pin_CN2_47_XBAR_INOUT pin_EMC_40
#define pyb_pin_CN2_27_XBAR_INOUT pin_EMC_41
