# Generated by make-pins.py, do NOT edit!
PINS_AF = (
  ('LED1', (1, 'LPI2C1_SCL'), (3, 'GPT3_COMPARE1'), (5, 'GPIO3_PIN7'), (10, 'GPIO9_PIN7'), (11, 'FLEXPWM1_PWMX2'), ),
  ('LED2', (1, 'LPI2C1_SDA'), (3, 'GPT3_COMPARE2'), (5, 'GPIO3_PIN8'), (10, 'GPIO9_PIN8'), (11, 'FLEXPWM1_PWMX3'), ),
  ('LED3', (3, 'GPT3_COMPARE3'), (5, 'GPIO3_PIN9'), (10, 'GPIO9_PIN9'), (11, 'FLEXPWM2_PWMX0'), ),
  ('LED4', (2, 'GPT1_CAPTURE2'), (5, 'GPIO3_PIN12'), (10, 'GPIO9_PIN12'), (11, 'FLEXPWM2_PWMX3'), ),
  ('KEY', (5, 'GPIO13_PIN0'), ),
)
