// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "180723_milestone-79-g95c2b14-dirty"
#define MICROPY_GIT_HASH "95c2b14-dirty"
#define MICROPY_BUILD_DATE "2019-12-17"
#define MICROPY_VERSION_MAJOR (0)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (1)
#define MICROPY_VERSION_STRING "0.0.1"
