// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "180723_milestone-27-g8dee74d-dirty"
#define MICROPY_GIT_HASH "8dee74d-dirty"
#define MICROPY_BUILD_DATE "2019-03-21"
#define MICROPY_VERSION_MAJOR (0)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (1)
#define MICROPY_VERSION_STRING "0.0.1"
