// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "1st_stable_1.9.3_port_with_demo-2-g5040133-dirty"
#define MICROPY_GIT_HASH "5040133-dirty"
#define MICROPY_BUILD_DATE "2018-01-07"
#define MICROPY_VERSION_MAJOR (0)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (1)
#define MICROPY_VERSION_STRING "0.0.1"
