// args= ['boards/make-pins.py', '--board', 'boards/omvrt1/pins.csv', '--af', 'boards/mimxrt105x_af.csv', '--prefix', 'boards/mimxrt105x_prefix.c', '--hdr', 'build-omvrt1/genhdr/pins.h', '--qstr', 'build-omvrt1/pins_qstr.h', '--af-const', 'build-omvrt1/genhdr/pins_af_const.h', '--pinmap', 'boards/mimxrt105x_pinmap.csv', '--af-py', 'build-omvrt1/pins_af.py']
// This file was automatically generated by make-pins.py
//
// --af boards/mimxrt105x_af.csv
// --pinmap boards/mimxrt105x_pinmap.csv
// --board boards/omvrt1/pins.csv
// --prefix boards/mimxrt105x_prefix.c

// <MCU>_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>

#include "py/obj.h"
#include "py/mphal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr, af_inSelReg, af_inSelVal) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .reg = (af_ptr), \
    .inSelReg = (af_inSelReg), \
    .inSelVal = (af_inSelVal), \
}

#define PIN(p_name, p_port, p_pin, p_af, p_adc_num, p_adc_channel, p_afReg, p_cfgReg) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_name, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (sizeof(p_af) / sizeof(pin_af_obj_t)), \
    .pin_mask = (1 << ((p_pin) & 0x0f)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
    .afReg = p_afReg, \
    .cfgReg = p_cfgReg, \
}

const pin_af_obj_t pin_AD_B0_12_af[] = {
  AF( 0, LPI2C   ,  4, SCL             , LPI2C4     , 0x401F84E4U, 0x1U), // LPI2C4_SCL
  //( 1, CCM     ,  0, PMIC_RDY        , CCM        , 0x401F83FCU, 0x1U), // CCM_PMIC_RDY
  AF( 2, LPUART  ,  1, TX              , LPUART1    , 0          , 0   ), // LPUART1_TX
  //( 3, WDOG    ,  2, WDOG_B          , WDOG2      , 0          , 0   ), // WDOG2_WDOG_B
  //( 4, FLEXPWM ,  1, PWMX2           , FLEXPWM1   , 0          , 0   ), // FLEXPWM1_PWMX2
  AF( 5, GPIO    ,  1, PIN12           , GPIO1      , 0          , 0   ), // GPIO1_PIN12
  //( 6, ENET    ,  0, 1588_EVENT1_OUT , ENET       , 0          , 0   ), // ENET_1588_EVENT1_OUT
  //( 7, CM      ,  7, NMI             , CM7        , 0x401F8568U, 0   ), // CM7_NMI
  //(15, AD      ,  0, B0_12           , AD         ,            ,     ), // AD_B0_12
};

const pin_obj_t pin_AD_B0_12 = PIN(AD_B0_12, 1, 12, pin_AD_B0_12_af, PIN_ADC1, 1, 0x401F80ECU, 0x401F82DCU);

const pin_af_obj_t pin_AD_B0_13_af[] = {
  AF( 0, LPI2C   ,  4, SDA             , LPI2C4     , 0x401F84E8U, 0x1U), // LPI2C4_SDA
  AF( 1, GPT     ,  1, CLK             , GPT1       , 0          , 0   ), // GPT1_CLK
  AF( 2, LPUART  ,  1, RX              , LPUART1    , 0          , 0   ), // LPUART1_RX
  //( 3, EWM     ,  0, EWM_OUT_B       , EWM        , 0          , 0   ), // EWM_EWM_OUT_B
  //( 4, FLEXPWM ,  1, PWMX3           , FLEXPWM1   , 0          , 0   ), // FLEXPWM1_PWMX3
  AF( 5, GPIO    ,  1, PIN13           , GPIO1      , 0          , 0   ), // GPIO1_PIN13
  //( 6, ENET    ,  0, 1588_EVENT1_IN  , ENET       , 0          , 0   ), // ENET_1588_EVENT1_IN
  //( 7, ANATOP  ,  0, 24M_OUT         , ANATOP     , 0          , 0   ), // ANATOP_24M_OUT
  //(15, AD      ,  0, B0_13           , AD         ,            ,     ), // AD_B0_13
};

const pin_obj_t pin_AD_B0_13 = PIN(AD_B0_13, 1, 13, pin_AD_B0_13_af, PIN_ADC1, 2, 0x401F80F0U, 0x401F82E0U);

const pin_af_obj_t pin_B1_15_af[] = {
  //( 0, ENET    ,  0, MDIO            , ENET       , 0x401F8430U, 0x2U), // ENET_MDIO
  //( 1, FLEXPWM ,  4, PWMA3           , FLEXPWM4   , 0x401F84A0U, 0x1U), // FLEXPWM4_PWMA3
  //( 2, CSI     ,  0, MCLK            , CSI        , 0          , 0   ), // CSI_MCLK
  //( 3, XBAR    ,  1, XBAR_IN3        , XBAR1      , 0x401F8610U, 0x1U), // XBAR1_XBAR_IN3
  //( 4, FLEXIO  ,  2, FLEXIO31        , FLEXIO2    , 0          , 0   ), // FLEXIO2_FLEXIO31
  AF( 5, GPIO    ,  2, PIN31           , GPIO2      , 0          , 0   ), // GPIO2_PIN31
  //( 6, USDHC   ,  1, RESET_B         , USDHC1     , 0          , 0   ), // USDHC1_RESET_B
  //( 7, TPSMP   ,  0, HDATA29         , TPSMP      ,            ,     ), // TPSMP_HDATA29
  //(15, B       ,  1, 15              , B1         ,            ,     ), // B1_15
};

const pin_obj_t pin_B1_15 = PIN(B1_15, 2, 31, pin_B1_15_af, 0, 0, 0x401F81B8U, 0x401F83A8U);

const pin_af_obj_t pin_EMC_11_af[] = {
  //( 0, SEMC    ,  0, ADDR2           , SEMC       , 0          , 0   ), // SEMC_ADDR2
  //( 1, FLEXPWM ,  2, PWMB2           , FLEXPWM2   , 0x401F8490U, 0x0U), // FLEXPWM2_PWMB2
  AF( 2, LPI2C   ,  4, SDA             , LPI2C4     , 0x401F84E8U, 0x0U), // LPI2C4_SDA
  //( 3, USDHC   ,  2, RESET_B         , USDHC2     , 0          , 0   ), // USDHC2_RESET_B
  //( 4, FLEXIO  ,  1, FLEXIO11        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO11
  AF( 5, GPIO    ,  4, PIN11           , GPIO4      , 0          , 0   ), // GPIO4_PIN11
  //( 6, ANATOP  ,  0, USBPHY2_TSTO_RX_HS_RXD, ANATOP     ,            ,     ), // ANATOP_USBPHY2_TSTO_RX_HS_RXD
  //( 7, SIM     ,  0, M_HADDR7        , SIM        ,            ,     ), // SIM_M_HADDR7
  //(15, EMC     ,  0, 11              , EMC        ,            ,     ), // EMC_11
};

const pin_obj_t pin_EMC_11 = PIN(EMC_11, 4, 11, pin_EMC_11_af, 0, 0, 0x401F8040U, 0x401F8230U);

const pin_af_obj_t pin_EMC_12_af[] = {
  //( 0, SEMC    ,  0, ADDR3           , SEMC       , 0          , 0   ), // SEMC_ADDR3
  //( 1, XBAR    ,  1, XBAR_IN24       , XBAR1      , 0x401F8640U, 0x0U), // XBAR1_XBAR_IN24
  AF( 2, LPI2C   ,  4, SCL             , LPI2C4     , 0x401F84E4U, 0x0U), // LPI2C4_SCL
  //( 3, USDHC   ,  1, WP              , USDHC1     , 0x401F85D8U, 0x0U), // USDHC1_WP
  //( 4, FLEXPWM ,  1, PWMA3           , FLEXPWM1   , 0x401F8454U, 0x1U), // FLEXPWM1_PWMA3
  AF( 5, GPIO    ,  4, PIN12           , GPIO4      , 0          , 0   ), // GPIO4_PIN12
  //( 6, ANATOP  ,  0, USBPHY1_TSTO_PLL_CLK20DIV, ANATOP     ,            ,     ), // ANATOP_USBPHY1_TSTO_PLL_CLK20DIV
  //( 7, SIM     ,  0, M_HADDR8        , SIM        ,            ,     ), // SIM_M_HADDR8
  //(15, EMC     ,  0, 12              , EMC        ,            ,     ), // EMC_12
};

const pin_obj_t pin_EMC_12 = PIN(EMC_12, 4, 12, pin_EMC_12_af, 0, 0, 0x401F8044U, 0x401F8234U);

const pin_af_obj_t pin_EMC_19_af[] = {
  //( 0, SEMC    ,  0, ADDR11          , SEMC       , 0          , 0   ), // SEMC_ADDR11
  //( 1, FLEXPWM ,  2, PWMA3           , FLEXPWM2   , 0x401F8474U, 0x1U), // FLEXPWM2_PWMA3
  AF( 2, LPUART  ,  4, TX              , LPUART4    , 0x401F8544U, 0x1U), // LPUART4_TX
  //( 3, ENET    ,  0, RDATA1          , ENET       , 0x401F8438U, 0x0U), // ENET_RDATA1
  //( 4, TMR     ,  2, TIMER0          , TMR2       , 0x401F856CU, 0x0U), // TMR2_TIMER0
  AF( 5, GPIO    ,  4, PIN19           , GPIO4      , 0          , 0   ), // GPIO4_PIN19
  //( 6, SNVS    ,  0, HP_VIO_5_B      , SNVS       , 0          , 0   ), // SNVS_HP_VIO_5_B
  //( 7, SIM     ,  0, M_HADDR15       , SIM        ,            ,     ), // SIM_M_HADDR15
  //(15, EMC     ,  0, 19              , EMC        ,            ,     ), // EMC_19
};

const pin_obj_t pin_EMC_19 = PIN(EMC_19, 4, 19, pin_EMC_19_af, 0, 0, 0x401F8060U, 0x401F8250U);

const pin_af_obj_t pin_EMC_20_af[] = {
  //( 0, SEMC    ,  0, ADDR12          , SEMC       , 0          , 0   ), // SEMC_ADDR12
  //( 1, FLEXPWM ,  2, PWMB3           , FLEXPWM2   , 0x401F8484U, 0x1U), // FLEXPWM2_PWMB3
  AF( 2, LPUART  ,  4, RX              , LPUART4    , 0x401F8540U, 0x1U), // LPUART4_RX
  //( 3, ENET    ,  0, RDATA0          , ENET       , 0x401F8434U, 0x0U), // ENET_RDATA0
  //( 4, TMR     ,  2, TIMER1          , TMR2       , 0x401F8570U, 0x0U), // TMR2_TIMER1
  AF( 5, GPIO    ,  4, PIN20           , GPIO4      , 0          , 0   ), // GPIO4_PIN20
  //( 6, ANATOP  ,  0, TESTO0          , ANATOP     ,            ,     ), // ANATOP_TESTO0
  //( 7, SIM     ,  0, M_HADDR16       , SIM        ,            ,     ), // SIM_M_HADDR16
  //(15, EMC     ,  0, 20              , EMC        ,            ,     ), // EMC_20
};

const pin_obj_t pin_EMC_20 = PIN(EMC_20, 4, 20, pin_EMC_20_af, 0, 0, 0x401F8064U, 0x401F8254U);

const pin_af_obj_t pin_EMC_21_af[] = {
  //( 0, SEMC    ,  0, BA0             , SEMC       , 0          , 0   ), // SEMC_BA0
  //( 1, FLEXPWM ,  3, PWMA3           , FLEXPWM3   , 0          , 0   ), // FLEXPWM3_PWMA3
  AF( 2, LPI2C   ,  3, SDA             , LPI2C3     , 0x401F84E0U, 0x0U), // LPI2C3_SDA
  //( 3, ENET    ,  0, TDATA1          , ENET       , 0          , 0   ), // ENET_TDATA1
  //( 4, TMR     ,  2, TIMER2          , TMR2       , 0x401F8574U, 0x0U), // TMR2_TIMER2
  AF( 5, GPIO    ,  4, PIN21           , GPIO4      , 0          , 0   ), // GPIO4_PIN21
  //( 6, ANATOP  ,  0, TESTO1          , ANATOP     ,            ,     ), // ANATOP_TESTO1
  //( 7, SIM     ,  0, M_HADDR17       , SIM        ,            ,     ), // SIM_M_HADDR17
  //(15, EMC     ,  0, 21              , EMC        ,            ,     ), // EMC_21
};

const pin_obj_t pin_EMC_21 = PIN(EMC_21, 4, 21, pin_EMC_21_af, 0, 0, 0x401F8068U, 0x401F8258U);

const pin_af_obj_t pin_EMC_22_af[] = {
  //( 0, SEMC    ,  0, BA1             , SEMC       , 0          , 0   ), // SEMC_BA1
  //( 1, FLEXPWM ,  3, PWMB3           , FLEXPWM3   , 0          , 0   ), // FLEXPWM3_PWMB3
  AF( 2, LPI2C   ,  3, SCL             , LPI2C3     , 0x401F84DCU, 0x0U), // LPI2C3_SCL
  //( 3, ENET    ,  0, TDATA0          , ENET       , 0          , 0   ), // ENET_TDATA0
  //( 4, TMR     ,  2, TIMER3          , TMR2       , 0x401F8578U, 0x0U), // TMR2_TIMER3
  AF( 5, GPIO    ,  4, PIN22           , GPIO4      , 0          , 0   ), // GPIO4_PIN22
  //( 6, ANATOP  ,  0, TESTO2          , ANATOP     ,            ,     ), // ANATOP_TESTO2
  //( 7, SIM     ,  0, M_HADDR18       , SIM        ,            ,     ), // SIM_M_HADDR18
  //(15, EMC     ,  0, 22              , EMC        ,            ,     ), // EMC_22
};

const pin_obj_t pin_EMC_22 = PIN(EMC_22, 4, 22, pin_EMC_22_af, 0, 0, 0x401F806CU, 0x401F825CU);

const pin_af_obj_t pin_EMC_27_af[] = {
  //( 0, SEMC    ,  0, CKE             , SEMC       , 0          , 0   ), // SEMC_CKE
  //( 1, FLEXPWM ,  1, PWMA2           , FLEXPWM1   , 0x401F8460U, 0x0U), // FLEXPWM1_PWMA2
  AF( 2, LPUART  ,  5, RTS_B           , LPUART5    , 0          , 0   ), // LPUART5_RTS_B
  AF( 3, LPSPI   ,  1, SCK             , LPSPI1     , 0x401F84F0U, 0x0U), // LPSPI1_SCK
  //( 4, FLEXIO  ,  1, FLEXIO13        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO13
  AF( 5, GPIO    ,  4, PIN27           , GPIO4      , 0          , 0   ), // GPIO4_PIN27
  //( 6, ANATOP  ,  0, TESTO7          , ANATOP     ,            ,     ), // ANATOP_TESTO7
  //( 7, SIM     ,  0, M_HADDR23       , SIM        ,            ,     ), // SIM_M_HADDR23
  //(15, EMC     ,  0, 27              , EMC        ,            ,     ), // EMC_27
};

const pin_obj_t pin_EMC_27 = PIN(EMC_27, 4, 27, pin_EMC_27_af, 0, 0, 0x401F8080U, 0x401F8270U);

const pin_af_obj_t pin_EMC_28_af[] = {
  //( 0, SEMC    ,  0, WE              , SEMC       , 0          , 0   ), // SEMC_WE
  //( 1, FLEXPWM ,  1, PWMB2           , FLEXPWM1   , 0x401F8470U, 0x0U), // FLEXPWM1_PWMB2
  AF( 2, LPUART  ,  5, CTS_B           , LPUART5    , 0          , 0   ), // LPUART5_CTS_B
  AF( 3, LPSPI   ,  1, SDO             , LPSPI1     , 0x401F84F8U, 0x0U), // LPSPI1_SDO
  //( 4, FLEXIO  ,  1, FLEXIO14        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO14
  AF( 5, GPIO    ,  4, PIN28           , GPIO4      , 0          , 0   ), // GPIO4_PIN28
  //( 6, ANATOP  ,  0, TESTO8          , ANATOP     ,            ,     ), // ANATOP_TESTO8
  //( 7, SIM     ,  0, M_HADDR24       , SIM        ,            ,     ), // SIM_M_HADDR24
  //(15, EMC     ,  0, 28              , EMC        ,            ,     ), // EMC_28
};

const pin_obj_t pin_EMC_28 = PIN(EMC_28, 4, 28, pin_EMC_28_af, 0, 0, 0x401F8084U, 0x401F8274U);

const pin_af_obj_t pin_EMC_29_af[] = {
  //( 0, SEMC    ,  0, CS0             , SEMC       , 0          , 0   ), // SEMC_CS0
  //( 1, FLEXPWM ,  3, PWMA0           , FLEXPWM3   , 0          , 0   ), // FLEXPWM3_PWMA0
  AF( 2, LPUART  ,  6, RTS_B           , LPUART6    , 0          , 0   ), // LPUART6_RTS_B
  AF( 3, LPSPI   ,  1, SDI             , LPSPI1     , 0x401F84F4U, 0x0U), // LPSPI1_SDI
  //( 4, FLEXIO  ,  1, FLEXIO15        , FLEXIO1    , 0          , 0   ), // FLEXIO1_FLEXIO15
  AF( 5, GPIO    ,  4, PIN29           , GPIO4      , 0          , 0   ), // GPIO4_PIN29
  //( 6, ANATOP  ,  0, TESTO9          , ANATOP     ,            ,     ), // ANATOP_TESTO9
  //( 7, SIM     ,  0, M_HADDR25       , SIM        ,            ,     ), // SIM_M_HADDR25
  //(15, EMC     ,  0, 29              , EMC        ,            ,     ), // EMC_29
};

const pin_obj_t pin_EMC_29 = PIN(EMC_29, 4, 29, pin_EMC_29_af, 0, 0, 0x401F8088U, 0x401F8278U);

const pin_af_obj_t pin_EMC_30_af[] = {
  //( 0, SEMC    ,  0, DATA8           , SEMC       , 0          , 0   ), // SEMC_DATA8
  //( 1, FLEXPWM ,  3, PWMB0           , FLEXPWM3   , 0          , 0   ), // FLEXPWM3_PWMB0
  AF( 2, LPUART  ,  6, CTS_B           , LPUART6    , 0          , 0   ), // LPUART6_CTS_B
  AF( 3, LPSPI   ,  1, PCS0            , LPSPI1     , 0x401F84ECU, 0x1U), // LPSPI1_PCS0
  //( 4, CSI     ,  0, DATA23          , CSI        , 0          , 0   ), // CSI_DATA23
  AF( 5, GPIO    ,  4, PIN30           , GPIO4      , 0          , 0   ), // GPIO4_PIN30
  //( 6, ANATOP  ,  0, TESTO10         , ANATOP     ,            ,     ), // ANATOP_TESTO10
  //( 7, SIM     ,  0, M_HADDR26       , SIM        ,            ,     ), // SIM_M_HADDR26
  //(15, EMC     ,  0, 30              , EMC        ,            ,     ), // EMC_30
};

const pin_obj_t pin_EMC_30 = PIN(EMC_30, 4, 30, pin_EMC_30_af, 0, 0, 0x401F808CU, 0x401F827CU);

const pin_af_obj_t pin_EMC_39_af[] = {
  //( 0, SEMC    ,  0, DQS             , SEMC       , 0          , 0   ), // SEMC_DQS
  //( 1, FLEXPWM ,  1, PWMB3           , FLEXPWM1   , 0x401F8464U, 0x2U), // FLEXPWM1_PWMB3
  AF( 2, LPUART  ,  8, RX              , LPUART8    , 0x401F8560U, 0x2U), // LPUART8_RX
#if (defined(MICROPY_HW_ENABLE_SAI3) && MICROPY_HW_ENABLE_SAI3)
  AF( 3, SAI     ,  3, TX_SYNC         , SAI3       , 0          , 0   ), // SAI3_TX_SYNC
#endif
  //( 4, WDOG    ,  1, WDOG_B          , WDOG1      , 0          , 0   ), // WDOG1_WDOG_B
  AF( 5, GPIO    ,  3, PIN25           , GPIO3      , 0          , 0   ), // GPIO3_PIN25
  //( 6, USDHC   ,  2, CD_B            , USDHC2     , 0x401F85E0U, 0x1U), // USDHC2_CD_B
  //( 7, SIM     ,  0, M_HBURST1       , SIM        ,            ,     ), // SIM_M_HBURST1
  //(15, EMC     ,  0, 39              , EMC        ,            ,     ), // EMC_39
};

const pin_obj_t pin_EMC_39 = PIN(EMC_39, 3, 25, pin_EMC_39_af, 0, 0, 0x401F80B0U, 0x401F82A0U);

const pin_af_obj_t pin_EMC_40_af[] = {
  //( 0, SEMC    ,  0, RDY             , SEMC       , 0          , 0   ), // SEMC_RDY
  AF( 1, GPT     ,  2, CAPTURE2        , GPT2       , 0          , 0   ), // GPT2_CAPTURE2
  //( 2, LPSPI   ,  1, PCS2            , LPSPI1     , 0          , 0   ), // LPSPI1_PCS2
  //( 3, USB     ,  0, OTG2_OC         , USB        , 0x401F85CCU, 0x1U), // USB_OTG2_OC
  //( 4, ENET    ,  0, MDC             , ENET       , 0          , 0   ), // ENET_MDC
  AF( 5, GPIO    ,  3, PIN26           , GPIO3      , 0          , 0   ), // GPIO3_PIN26
  //( 6, USDHC   ,  2, RESET_B         , USDHC2     , 0          , 0   ), // USDHC2_RESET_B
  //( 7, SIM     ,  0, M_HBURST2       , SIM        ,            ,     ), // SIM_M_HBURST2
  //(15, EMC     ,  0, 40              , EMC        ,            ,     ), // EMC_40
};

const pin_obj_t pin_EMC_40 = PIN(EMC_40, 3, 26, pin_EMC_40_af, 0, 0, 0x401F80B4U, 0x401F82A4U);

const pin_af_obj_t pin_EMC_41_af[] = {
  //( 0, SEMC    ,  0, CSX0            , SEMC       , 0          , 0   ), // SEMC_CSX0
  AF( 1, GPT     ,  2, CAPTURE1        , GPT2       , 0          , 0   ), // GPT2_CAPTURE1
  //( 2, LPSPI   ,  1, PCS3            , LPSPI1     , 0          , 0   ), // LPSPI1_PCS3
  //( 3, USB     ,  0, OTG2_PWR        , USB        , 0          , 0   ), // USB_OTG2_PWR
  //( 4, ENET    ,  0, MDIO            , ENET       , 0x401F8430U, 0x1U), // ENET_MDIO
  AF( 5, GPIO    ,  3, PIN27           , GPIO3      , 0          , 0   ), // GPIO3_PIN27
  //( 6, USDHC   ,  1, VSELECT         , USDHC1     , 0          , 0   ), // USDHC1_VSELECT
  //(15, EMC     ,  0, 41              , EMC        ,            ,     ), // EMC_41
};

const pin_obj_t pin_EMC_41 = PIN(EMC_41, 3, 27, pin_EMC_41_af, 0, 0, 0x401F80B8U, 0x401F82A8U);

const pin_af_obj_t pin_WAKEUP_af[] = {
  AF( 5, GPIO    ,  5, PIN0            , GPIO5      , 0          , 0   ), // GPIO5_PIN0
};

const pin_obj_t pin_WAKEUP = PIN(WAKEUP, 5, 0, pin_WAKEUP_af, 0, 0, 0x400A8000U, 0x400A8018U);

STATIC const mp_rom_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_AD_B0_12), MP_ROM_PTR(&pin_AD_B0_12) },
  { MP_ROM_QSTR(MP_QSTR_AD_B0_13), MP_ROM_PTR(&pin_AD_B0_13) },
  { MP_ROM_QSTR(MP_QSTR_B1_15), MP_ROM_PTR(&pin_B1_15) },
  { MP_ROM_QSTR(MP_QSTR_EMC_11), MP_ROM_PTR(&pin_EMC_11) },
  { MP_ROM_QSTR(MP_QSTR_EMC_12), MP_ROM_PTR(&pin_EMC_12) },
  { MP_ROM_QSTR(MP_QSTR_EMC_19), MP_ROM_PTR(&pin_EMC_19) },
  { MP_ROM_QSTR(MP_QSTR_EMC_20), MP_ROM_PTR(&pin_EMC_20) },
  { MP_ROM_QSTR(MP_QSTR_EMC_21), MP_ROM_PTR(&pin_EMC_21) },
  { MP_ROM_QSTR(MP_QSTR_EMC_22), MP_ROM_PTR(&pin_EMC_22) },
  { MP_ROM_QSTR(MP_QSTR_EMC_27), MP_ROM_PTR(&pin_EMC_27) },
  { MP_ROM_QSTR(MP_QSTR_EMC_28), MP_ROM_PTR(&pin_EMC_28) },
  { MP_ROM_QSTR(MP_QSTR_EMC_29), MP_ROM_PTR(&pin_EMC_29) },
  { MP_ROM_QSTR(MP_QSTR_EMC_30), MP_ROM_PTR(&pin_EMC_30) },
  { MP_ROM_QSTR(MP_QSTR_EMC_39), MP_ROM_PTR(&pin_EMC_39) },
  { MP_ROM_QSTR(MP_QSTR_EMC_40), MP_ROM_PTR(&pin_EMC_40) },
  { MP_ROM_QSTR(MP_QSTR_EMC_41), MP_ROM_PTR(&pin_EMC_41) },
  { MP_ROM_QSTR(MP_QSTR_WAKEUP), MP_ROM_PTR(&pin_WAKEUP) },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_rom_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_LED_R), MP_ROM_PTR(&pin_EMC_39) },
  { MP_ROM_QSTR(MP_QSTR_LED_G), MP_ROM_PTR(&pin_EMC_40) },
  { MP_ROM_QSTR(MP_QSTR_LED_B), MP_ROM_PTR(&pin_EMC_41) },
  { MP_ROM_QSTR(MP_QSTR_LED_IR), MP_ROM_PTR(&pin_B1_15) },
  { MP_ROM_QSTR(MP_QSTR_KEY), MP_ROM_PTR(&pin_WAKEUP) },
  { MP_ROM_QSTR(MP_QSTR_DBG_RXD), MP_ROM_PTR(&pin_AD_B0_13) },
  { MP_ROM_QSTR(MP_QSTR_DBG_TXD), MP_ROM_PTR(&pin_AD_B0_12) },
  { MP_ROM_QSTR(MP_QSTR_UART4_TXD), MP_ROM_PTR(&pin_EMC_19) },
  { MP_ROM_QSTR(MP_QSTR_UART4_RXD), MP_ROM_PTR(&pin_EMC_20) },
  { MP_ROM_QSTR(MP_QSTR_SDO), MP_ROM_PTR(&pin_EMC_28) },
  { MP_ROM_QSTR(MP_QSTR_SDI), MP_ROM_PTR(&pin_EMC_29) },
  { MP_ROM_QSTR(MP_QSTR_SCK), MP_ROM_PTR(&pin_EMC_27) },
  { MP_ROM_QSTR(MP_QSTR_PCSO), MP_ROM_PTR(&pin_EMC_30) },
  { MP_ROM_QSTR(MP_QSTR_SDA3), MP_ROM_PTR(&pin_EMC_21) },
  { MP_ROM_QSTR(MP_QSTR_SCL3), MP_ROM_PTR(&pin_EMC_22) },
  { MP_ROM_QSTR(MP_QSTR_SDA4), MP_ROM_PTR(&pin_EMC_11) },
  { MP_ROM_QSTR(MP_QSTR_SCL4), MP_ROM_PTR(&pin_EMC_12) },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[] = {
  NULL,    // 0
  &pin_AD_B0_12, // 1
  &pin_AD_B0_13, // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
  NULL,    // 16
};

const pin_obj_t * const pin_adc2[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
  NULL,    // 16
};
